- artiq/dashboard/moninj.py
- artiq/runtime/moninj.c
See GitHub #601 and the individual commit messages for details.
I've made this PR against the `release-2` branch since it fixes a nasty surprise and is minimally invasive, but I'd be happy to open a PR against the Rust runtime in master as well.
> Don't try to handle more than 64 channels in moninj

- artiq/language/environment.py
Could this also be cherry-picked onto release-2?
> language: fix PYONValue list defaults (fixes #682)

- artiq/coredevice/sampler.py
Replaces #972
Context:
- Currently `adc_mu_to_volt` takes a parameter `v_ref`
- This parameter isn't necessary, since there are no plans to make the reference voltage switchable on Sampler 
- The way the code is written is a bit confusing, since passing `v_ref=5.` (the default value) does not give the correct mu->input voltage conversion, since `adc_mu_to_volt` does not take account of the gain of the differential input stage. 
- `Sampler` internally uses `v_ref=10.`, which is confusing, since (a) this isn't the reference voltage used in the PCB/schematic (b) it's not the default value, so passing the output of `sample` dumbly into `adc_mu_to_volt` gives the wrong answer.
@jordens apologies, I haven't got HW set up to test this atm, but I wanted to get this off my to do list. Do you mind …
> Remove Sampler v_ref parameter.

- .github/pull_request_template.md
PR template wasn't in a logical order, hard for maintainers to read. Reorganized.
Fix directory where docs are built from.
#1163 
|   | Type |
> [template]: Reorder pull request template

- .github/ISSUE_TEMPLATE/3_Question.md
Question.md didn't display on ARTIQ new issue page.
Solution: Cannot use ":" in Markdown header
|   | Type |
> [bug]: fix question issue template use of ":"

- artiq/coredevice/ad9910.py
- artiq/coredevice/ttl.py
- artiq/coredevice/urukul.py
- artiq/examples/kasli_basic/device_db_luh.py
- artiq/examples/kasli_basic/device_db_opticlock.py
- artiq/examples/kasli_basic/device_db_ptb.py
- artiq/examples/kasli_basic/device_db_ptb2.py
- artiq/examples/kasli_tester/device_db.py
- artiq/gateware/eem.py
- artiq/gateware/targets/kasli.py
- artiq/test/coredevice/test_ad9910.py
- artiq/test/coredevice/test_urukul.py
Closes #1143 
See roadmap and milestones there.
|   | Type |
```
```
> Urukul sync

- artiq/coredevice/ad9910.py
close #1154
|   | Type |
Roadmap:
```
```
> ad9910: add RAM mode methods

- doc/manual/installing.rst
Previous docs assumed knowledge of how to check if you're in plugdev. Add one line to explain how to check this.
> Docs: instructions to check if in plugdev group

- artiq/protocols/pyon.py
> pyon: fix grammar in module docstring.

- artiq/frontend/artiq_client.py
Simplify input verification (command-line argument) logic by using built-ins from `argparse`.
None
|   | Type |
- NOTE: fixed `flake8` errors from pre-existing code too.
- Tested by running commands from command line: `artiq_client show fake`, `artiq_client show devices`, `artiq_client set-dataset -p -n`
```
[topic]: description. < 50 characters total.
```
> [artiq_client]: Remove custom input validation for built-in argparse

- doc/manual/getting_started_core.rst
- doc/manual/utilities.rst
See #1232, #206, #550.
Signed-off-by: Drew Risinger <drewrisinger@users.noreply.github.com>
> Docs: document artiq_coreanalyzer usage.

- RELEASE_NOTES.rst
- artiq/frontend/aqctl_korad_ka3005p.py
- artiq/frontend/aqctl_lda.py
- artiq/frontend/aqctl_novatech409b.py
- artiq/frontend/aqctl_thorlabs_tcube.py
- artiq/frontend/artiq_browser.py
- artiq/frontend/artiq_client.py
- artiq/frontend/artiq_compile.py
- artiq/frontend/artiq_coreanalyzer.py
- artiq/frontend/artiq_coremgmt.py
- artiq/frontend/artiq_ctlmgr.py
- artiq/frontend/artiq_dashboard.py
- artiq/frontend/artiq_devtool.py
- artiq/frontend/artiq_flash.py
- artiq/frontend/artiq_influxdb.py
- artiq/frontend/artiq_run.py
- artiq/tools.py
- doc/manual/developing_a_ndsp.rst
Rename `verbosity_args()` to `add_common_args()`. Add option for `--version`.
Use `process_common_args()` instead of `init_logger()`. Rename `init_logger()` to `_init_logger()` because deprecated.
Closes #1160
|   | Type |
> [tools]: Add --version flag to cmd line args

- .github/ISSUE_TEMPLATE/3_Question.md
Add a line to the github issue template to remind users to consider contributing to the ARTIQ documentation after asking questions. While we're at it, fix some errant white space. 
|   | Type |
```
```
> issue template: remind users to update the docs

- artiq/dashboard/moninj.py
* handle disconnects like core device address changes and do a
disconnect/connect iteration
* after connection failure wait 10 seconds and try again
* this addresses the slight regression from release-2
to release-3 where the moninj protocol was made stateful
(#838 and #1125)
* it would be much better to fix smoltcp/runtime to no loose the
connection under pressure (#1125)
* the crashes reported in #838 look more like a race condition
* master disconnects still require dashboard restarts
Signed-off-by: Robert Jördens <rj@quartiq.de>
#1125 
#838 
|   | Type |
``` …
```
> dashboard: reconnect to core moninj

- artiq/frontend/artiq_run.py
- artiq/test/test_datasets.py
Update dataset tests and artiq_run - fixes #1290
> fix tests, artiq_run after implementing scheduler defaults (#1290)

- artiq/frontend/artiq_compile.py
Closes #1290
I don't know how to trigger the buildbot to build from this PR - can anyone tell me how?
> artiq_compile: fix after adding scheduler defaults

- artiq/compiler/builtins.py
- artiq/compiler/prelude.py
- artiq/compiler/transforms/artiq_ir_generator.py
- artiq/compiler/transforms/inferencer.py
- artiq/test/lit/inferencer/builtin_calls.py
- artiq/test/lit/inferencer/error_builtin_calls.py
- artiq/test/lit/integration/abs.py
> compiler: Implement abs() for scalars

- artiq/protocols/sync_struct.py
sync_struct white space changes according to flake8. NFC
> sync_struct: flake8 [nfc]

- doc/manual/management_system.rst
Document interactions between events created by different experiments
|   | Type |
> Scheduler documentation: interaction between experiments

- artiq/coredevice/suservo.py
Additional pull request related to https://github.com/m-labs/artiq/pull/1327#issuecomment-497064216
|   | Type |
See https://github.com/m-labs/artiq/pull/1327#issue-281271420
```
```
> suservo coredevice driver: mask ftw to avoid erroneous sign extension

- artiq/frontend/artiq_influxdb_schedule.py
Fixes error in parameter name for DBWriter.update() call. Also adds logging to stderr for unhandled exceptions in Subscriber._receive_cr(). 
|   | Type |
> Correct error in artiq_influxdb_schedule

- artiq/protocols/pyon.py
Correctly decode "inf" in pyon encoded strings. 
|   | Type |
> pyon: Handle inf in decoding

- artiq/tools.py
Wraps the _do() method of a TaskObject, called in TaskObject.start(), in an exception handler to catch and relaunch the method in case of exceptions and log this to the logger. 
|   | Type |
The `_do()` method in many concrete implementations of TaskObjects implements error handling, but this is not universal. In e.g. 
https://github.com/m-labs/artiq/blob/98caaebaded20ebc02e9200a9e31ea8f47a8b84a/artiq/frontend/artiq_influxdb.py#L99-L121
...exceptions occuring in the first part will not be caught, causing the Task to end with no error message either on failure or subsequent write attempts. 
This commit wraps the `TaskObject._do()` method in a generic last-line-of-defense task handler, and restarts the method if an unhandled error …
> tools: Wrap Task _do() calls in a generic exception handler

- artiq/coredevice/ad9910.py
- artiq/coredevice/ad9912.py
- artiq/coredevice/urukul.py
Add documentation to all urukul-related functions that overwrite the attenuator settings of other channels. Document that the result of `CPLD.get_att_mu()` is stored and used in future calls of `CPLD.set_att_mu()`.
Closes #1386 
|   | Type |
```
```
> Improve documentation of urukul attenuator behavior

- artiq/frontend/artiq_ddb_template.py
Add minimal Mirny support for ``artiq_ddb_template``.
Targets CPLD gateware v.0.2.1 from quartiq/mirny#1.
Tested against coredevice driver from #1405.
Augments #1405. Addresses #1130.
|   | Type |
```
```
> artiq_ddb_template: add Mirny support

- artiq/coredevice/fastino.py
- artiq/frontend/artiq_ddb_template.py
- artiq/gateware/eem.py
- artiq/gateware/rtio/phy/fastino.py
- artiq/gateware/targets/kasli_generic.py
- doc/manual/core_drivers_reference.rst
* Tested on Fastino prototype
* All working except the state readback
implements part of #1373 
|   | Type |
```
```
> Fastino: add [WIP]

- RELEASE_NOTES.rst
- artiq/coredevice/ad9910.py
- artiq/coredevice/ad9912.py
- artiq/coredevice/ad9914.py
- artiq/coredevice/suservo.py
- artiq/coredevice/urukul.py
Signed-off-by: Marius Weber <marius.weber@physics.ox.ac.uk>
Add input validation and masking to SI -> machine-unit conversions.
This follows the discussion in #1446.
|   | Type |
|  | :hammer: Refactoring  |
> Coredevice Input Validation

- artiq/dashboard/applets_ccb.py
Restart existing applets if their spec changes
Add a call to `applet_dock.restart()` when applets' specs are updated via a ccb while they're already running.
|   | Type |
```
```
> Restart applets if required

- RELEASE_NOTES.rst
> dashboard: Release notes for #1453

- artiq/frontend/artiq_sinara_tester.py
This enables testing Fastino on Kasli.
Using this updated code for [artiq_sinara_tester](artiq/frontend/artiq_sinara_tester.py), the user can now:
* test the 32-channel DACs on each Fastino card; and
* test switching on and off each of the front-panel user LEDs on each Fastino device:
* Each LEDs across all connected Fastino cards blinks in the ascending order of card number and LED number.
The Fastino cards are tested right after all Zotino cards finish testing. Once the test begins, all DACs of all connected Fastino cards have their voltage set at once, and the LEDs start blinking in the order shown above. To end the test, the user only needs to press Enter once.
> fastino: add tests for artiq_sinara_tester

- artiq/frontend/artiq_sinara_tester.py
This enables LED testing for Zotino.
This updated code for [artiq_sinara_tester](artiq/frontend/artiq_sinara_tester.py) lets the user test switching on and off each of the front-panel user LEDs on each Zotino device. Each LEDs across all connected Zotino cards blinks in the ascending order of card number and LED number.
The portion of LED blinking takes place the same time as the portion of DAC voltage testing. To end both portion of the test, the user only needs to press Enter once. This is similar to the test added for Fastino on #1459.
> zotino: add USER LED test for artiq_sinara_tester

- doc/manual/rtio.rst
#ARTIQ Pull Request
|   | Type |
Add a couple of sentences explaining how SED sequencing works and how sequencing errors can occur. 
> Docs RTIO sequencing a bit

- artiq/master/scheduler.py
- artiq/test/test_scheduler.py
@pmldrmota: This should do it.
> master/scheduler: Fix priority/due date precedence order when waiting to prepare

- artiq/gateware/drtio/wrpll/si549.py
wrpll: fix scl signal
|   | Type |
> wrpll: fix scl signal

- artiq/gateware/drtio/wrpll/si549.py
wrpll: fix run signal
|   | Type |
```
```
> wrpll: fix run signal

- artiq/coredevice/ad9910.py
Write correct number of bits to POW register in `set_pow` to avoid symptom #1141. 
Moreover, return type hints resolve occasional compiler type inference issues.
Prevents manifestation of #1141
|   | Type |
```
```
> AD9910: Write correct number of bits to POW register

- RELEASE_NOTES.rst
- artiq/build_soc.py
- artiq/gateware/targets/kasli.py
- artiq/gateware/targets/kasli_generic.py
- artiq/gateware/targets/kc705.py
- artiq/gateware/targets/metlino.py
- artiq/gateware/targets/sayma_amc.py
- artiq/gateware/targets/sayma_rtm.py
|   | Type |
|    | :bug: Bug fix  |
|    | :hammer: Refactoring  |
|    | :scroll: Docs |
```
```
> build_soc: add identifier_str override option

- artiq/build_soc.py
- artiq/gateware/targets/kasli.py
- artiq/gateware/targets/kasli_generic.py
- artiq/gateware/targets/kc705.py
- artiq/gateware/targets/metlino.py
- artiq/gateware/targets/sayma_amc.py
- artiq/gateware/targets/sayma_rtm.py
> build_soc: rename identifier_str to gateware_identifier_str

- artiq/compiler/transforms/inferencer.py
- artiq/compiler/transforms/llvm_ir_generator.py
- artiq/test/coredevice/test_embedding.py
- artiq/test/lit/integration/array.py
Fixes #1523; here to test Hydra integration.
> compiler: Array quoting fixes

- artiq/coredevice/phaser.py
Fix typos in phaser coredevice driver docstring.
|   | Type |
```
```
> coredevice/phaser: fix typo in docstring

- artiq/frontend/artiq_sinara_tester.py
|   | Type |
|  x | :hammer:  refactoring
Tested artiq_sinara_tester using nix-shell on new Sinara system with Urukul.
> modified urukul instructions in sinara tester script

- artiq/frontend/artiq_ddb_template.py
Fixed the nr. of phaser rtio channels.
|   | Type |
> Phased ddb fix

- artiq/frontend/artiq_ddb_template.py
This PR adds default values to Mirny CPLD. #1561 breaks existing JSON configurations involving Mirny.
It aims to make #1561 backward-compatible.
- Default value of `clk_sel` is `0` (internal XO)
- Default value of `refclk` is `100MHz` (internal XO frequency)
Using old JSON ocnfiguration for Mirny: (i.e. without `clk_sel` and `refclk)
```json
{
"type": "mirny",
"ports": [1]
},
```
The following descriptions will be generated for `mirny_cpld`:
```python
device_db["mirny0_cpld"] = {
"type": "local",
"module": "artiq.coredevice.mirny",
"class": "Mirny",
"arguments": {
"spi_device": "spi_mirny0",
"refclk": 100000000.0,
"clk_sel": 0
},
}
```
With new JSON confugrations such as:
```json
{
"type": "mirny",
"ports": [8],
"clk_sel": 1,
"refclk": 125e6
},
```
These descriptions for `mirny_cpld` will …
> artiq_ddb_template: add default value for Mirny CPLD parameters

- artiq/frontend/artiq_sinara_tester.py
This PR adds a test for `Mirny` (v1.1 specifically) in `artiq_sinara_tester`.
|   | Type |
Successfully tested a ARTIQ system with Mirny card with this `artiq_sinara_tester.py`.
Albeit Mirny issue stated in #1560 may occur.
```
```
> sinara_tester: Add Mirny test

- MANIFEST.in
- RELEASE_NOTES.rst
- artiq/frontend/artiq_ddb_template.py
- artiq/gateware/jsondesc.py
- artiq/gateware/targets/kasli_generic.py
- artiq/gateware/targets/kasli_generic.schema.json
A take on #1474.
|   | Type |
|    | :bug: Bug fix  |
|    | :hammer: Refactoring  |
```
```
> JSON schema

- artiq/firmware/libproto_artiq/rpc_proto.rs
Optimize integer array/list device-to-host RPC.
As the device is in big endian, we can cast the slice into byte slice, directly copy from slice instead of calling `write_u32`/`write_u64` repeatedly. This improves the performance quite a lot.
| Test                 | Prev (MiB/s) | Now (MiB/s)  |  diff  |
| -------------------- | ------------ | ------------ | ------ |
| I32 Array (1MB) H2D  |         2.02 |         2.06 | +1.90% |
| I32 Array (1MB) D2H  |         0.48 |         2.23 |  +365% |
| I32 Array (1KB) H2D  |         0.36 |         0.35 | -2.78% |
| I32 Array (1KB) D2H  |         0.23 |         0.38 | +65.2% |
| I32 List (1MB) H2D   |         2.07 |         2.00 | -3.38% |
| I32 List (1MB) D2H   |         0.45 |         2.18 |  +384% |
| I32 List (1KB) H2D   |         0.35 | …
> firmware: optimize integer array/list rpc

- RELEASE_NOTES.rst
- artiq/coredevice/coredevice_generic.schema.json
- artiq/gateware/targets/kasli_generic.py
This will allow us to get rid of the static variants list in nix-scripts by replacing it with a `builtins.readDir` of sinara-systems, filtered by `"min_artiq_version"` for the non-beta and beta jobsets.
Once this information is added, let's act on it and warn the user. Should we throw a terminal exception instead?
|   | Type |
|    | :bug: Bug fix  |
|    | :hammer: Refactoring  |
|    | :scroll: Docs |
```
```
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed …
> Add "min_artiq_version" to kasli JSON descriptions

- artiq/master/worker_impl.py
Resolves error message shown.
The following error message is shown when worker_impl.py:199 is run: 
```
WARNING:worker(RID,EXPERIMENT):py.warnings:/nix/store/77sw4p03cb7rdayx86agi4yqxh5wq46b-python3.7-artiq-5.7141.1b68906/lib/python3.7/site-packages/artiq/master/worker_impl.py:199: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
logging.warn(message)
```
None
|   | Type |
```
```
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under …
> master: fix DeprecationWarning on logger.warn

- artiq/coredevice/coredevice_generic.schema.json
Closes #1602 
|   | Type |
|    | :bug: Bug fix  |
| ✓ | :sparkles: New feature |
|    | :hammer: Refactoring  |
|    | :scroll: Docs |
> jsonschema: validate hw_dev depending on target

- doc/manual/developing_a_ndsp.rst
Added section to manual outlining how to integrate NDSP controller into device_db.py
Added documentation for integrating NDSP in artiq and reference to artiq_ctlmgr
|   | Type |
```
```
> Updated NDSP documentation

- artiq/language/scan.py
1. added abstract `describe()` function to `ScanObject` (improves inheritance and typing)
1. replaced deprecated `inspect.getargspec()` with `inspect.getfullargspec()` in `Scannable`
|   | Type |
```
```
> ScanObject and Scannable minor improvements

- RELEASE_NOTES.rst
- artiq/coredevice/ad9910.py
- artiq/coredevice/ad9912.py
- artiq/coredevice/urukul.py
- artiq/test/coredevice/test_ad9910.py
- artiq/test/coredevice/test_urukul.py
Added `get()` and `get_mu()`, `get_att()`, and `get_att_mu()` functions for the AD9910 and AD9912 coredevice drivers.
Closes #1616 
|   | Type |
```
```
> added functions to get freq/phase/amp/att for ad99xx and urukul

- artiq/language/environment.py
- artiq/language/scan.py
Minor improvements. Added abstract `__iter__()` and `__len__()` methods to the `ScanObject` class for nicer inheritance. And at the same time I realized `DefaultMissing` was not in `__all__`.
Could potentially also be applied to `release-6` and older releases.
|   | Type |
```
```
> Extended ScanObject abstract methods

- doc/manual/compiler.rst
Adds a note in the `Compiler` section about using empty lists in the kernel.
Closes #1669.
|   | Type |
```
```
> manual: cannot use empty lists in kernel

- artiq/frontend/aqctl_corelog.py
Fixed according to
https://forum.m-labs.hk/d/190-fetchingreading-the-core-log-in-a-central-location/10
Tested with both KC705 and ZC706.
Closes #1682
|   | Type |
```
```
> aqctl_corelog: fix #1682

- artiq/test/test_device_db.py
Fixes ``test_device_db.py`` on Windows. Crash was due to access limitations on Windows when using ``delete=True`` in ``tempfile.NamedTemporaryFile``. See e.g. [here](https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file).
https://github.com/m-labs/artiq/pull/1699#issuecomment-864417563
|   | Type |
```
```
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are …
> test_device_db: fix on Windows (tempfile access limitations)

- artiq/coredevice/mirny.py
- doc/manual/faq.rst
- doc/manual/rtio.rst
- Fixes #1684 by using ``delay`` instead of ``delay_mu``, since ``coarse_ref_period`` is already available in the core instances. Exposing ``coarse_ref_period_mu = core.seconds_to_mu(coarse_ref_period)`` would also be an option but results in more verbose user code. For consistency, one would also need to update an number of coredevice drivers (``spi2``, ``grabber``, ``sawg``, ``suservo``) which is quite intrusive.
- Fix miscellaneous formatting issues in the docs.
|   | Type |
```
``` …
> docs: fix RTIO coarse delay snippet and misc. formatting

- artiq/compiler/embedding.py
- artiq/compiler/transforms/llvm_ir_generator.py
Speedup computation related to list by manual inlining and removing redundant computation. (The embedding module is crazily slow due to a lot of string operations...)
Tested with two simple programs with large arrays:
Ordinary lists:
```python
class Test(EnvExperiment):
self.array = list(range(100000))
@kernel
def run(self):
i = 0.0
for x in self.array:
i += x
return i
```
Compile time before and after the patch:
```sh
$ time artiq_compile array_test.py
artiq_compile array_test.py  1.50s user 0.05s system 100% cpu 1.543 total
$ export PYTHONPATH=$HOME/code/artiq:$PYTHONPATH
$ time artiq_compile array_test.py
artiq_compile array_test.py  0.68s user 0.04s system 100% cpu 0.717 total
```
Numpy arrays (tested with 1D …
> compiler: speedup list processing

- RELEASE_NOTES.rst
- artiq/compiler/transforms/inferencer.py
Supports kernel decorator with path. Example:
```python
import artiq.experiment as exp
class Test(exp.EnvExperiment):
@exp.kernel
def run(self):
pass
```
Closes #1162.
|   | Type |
```
```
> compiler: supports kernel decorator with path

- artiq/compiler/embedding.py
- artiq/compiler/types.py
Improves type checking performance.
We need to check if our inference reached a fixed point. This is checked
using the hash of the types in the AST, which is very slow. This patch
avoids computing the hash if we can make sure that the AST is definitely
changed, which is when we parse a new function.
For example, consider the following script (generated):
```python
class Test(EnvExperiment):
@kernel
def run(self):
print(self.method_0(1))
@kernel
def method_0(self, v):
return self.method_1(v)
...
@kernel
def method_199(self, v):
return self.method_200(v)
@kernel
def method_200(self, v):
return v
```
This took 3.3s prior to this patch, and now takes 2.25s.
The find implementation was not very optimized, and the unify …
> Compiler: Improve type checking performance

- .gitignore
- artiq/dashboard/datasets.py
Adding new datasets function in artiq_dashboard. The users can type in the name and value of the datasets in corresponding boxes. The data type will be shown next to the value box in real-time. It will show "N/A" if the input cannot be recognized and if the user still hits enter it will not proceed but show a log error. The decoder is `sipyco::pyon`
Warn!: string should be input like `"something"` with a double-quote.
Closes #1707 
|   | Type |
```
```
ARTIQ files that do not contain a license header are …
> GUI: create new datasets

- artiq/applets/plot_hist.py
Display a warning message on the plot window if the length of dataset X is not 1 longer than that of Y after a timeout of 0.5s. However, if the change in the dataset is less than the timeout, it will not display anything unless we change the dataset again. The display is as shown below:
Closes #1702 
|   | Type |
```
```
> applets: add warning message on plot for plot_hist

- doc/manual/utilities.rst
In the artiq documentation, an example that removes the config key shows `$ artiq_coremgmt config delete my_key`. However, there is no `delete` in the possible choices but `remove` instead.
|   | Type |
```
```
> documentation: correct artiq_coremgmt examples

- artiq/applets/plot_hist.py
applets: make sure the warning is shown right after the timeout of the happening of the first failure
>With your previous PR and this one, if you regularly send data that produces a mismatch every time, it will not trigger the warning AFAICT (but it should). This is due to the timer being constantly restarted before it can fire.
Check timer active status before starting the timer.
|   | Type |
```
```
> applets: warning timing improvement

- artiq/applets/plot_xy.py
Display a warning message on the plot window if the datasets do not satisfy some conditions after a timeout of 1s.
For the `plot_xy` applet, the length of X values, error bars, fit values should have the same length as Y values. If any of these isn't satisfied, the plot won't show anything except the warning message. The display is as shown below:
|   | Type |
```
```
> applets: add warning message on plot for `plot_xy`

- artiq/applets/plot_xy_hist.py
For the `plot_xy_hist` applet, the length of bin boundaries should be the same as the first dimension of histogram counts, and the length of point abscissas should be the same as the second dimension of histogram counts. Either failure will cause the xy plot to fail to display. The warning message is as shown below:
Potential bug fix: previously the histogram plot will crash in all my testing cases. Now, it will show `click on the data point at left to see histogram` if the xy plot is shown.
Closes #1702 
|   | Type |
```
``` …
> applets: add warning message on plot for `plot_xy_hist and fix bug`

- artiq/firmware/libboard_misoc/spiflash.rs
- artiq/firmware/runtime/main.rs
Use `cfg` condition to prevent sayma from using ICAP
|   | Type |
```
```
> ICAP: prevent sayma from using it

- artiq/gateware/drtio/transceiver/gtx_7series.py
- artiq/gateware/targets/kc705.py
This pull request is a part of three ( m-labs/migen#243, nix-scripts, this) which bring GTX transceiver class interface closer to reference (Kasli). This one in particular refers to new signal definitions from Migen PR, where sfp/sma signals have 4 subsignals (rx/tx, p/n) instead of being separate signals with only p/n subsignals.
This PR should be merged last.
|   | Type |
Only checked that it compiles succesfully in all four relevant variants (nist_clock/nist_qc2, master/satellite). Probably would be best to check if it works on kc705 board properly, although with no changes in logic I'm not sure if it's really necessary.
```
topic: description. < …
```
> kc705/gtx interface more similar to kasli/gtp

- RELEASE_NOTES.rst
- artiq/coredevice/coredevice_generic.schema.json
- artiq/frontend/artiq_ddb_template.py
- artiq/gateware/eem.py
- artiq/gateware/eem_7series.py
Added support for [HV_AMP_8CH](https://github.com/sinara-hw/HV_AMP_8CH)
|   | Type |
Tested with minimal setup using Kasli, Zotino and HVAMP.
> Added support for HVAMP_8CH

- RELEASE_NOTES.rst
- artiq/frontend/artiq_ddb_template.py
Modified the keys generated for edge counter devices when using `artiq_ddb_template`.
Previously `ttl_counter_0` and `ttl_0` could be on completely different physical TTL output channels.
With this change, `ttl_0_counter` (note the changed key format) is always on the same channel as `ttl_0`.
None
|   | Type |
```
```
> ddb_template: edge counter keys correspond with according ttl keys

- artiq/frontend/artiq_sinara_tester.py
This patch adds the following command line options to the `artiq_sinara_tester`:
- `--device-db`: select the `device_db.py` file to use (instead of default `./device_db.py`)
- `--only`: only run certain tests
- `--exclude`: do not run certain tests
Functionality was tested on hardware. When using no options or `--exclude`, the test execution order is preserved. When using `--only`, the tests are executed in the listed order.
|   | Type |
```
```
See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign …
> sinara_tester: add device_db and test selection CLI options

- artiq/language/types.py
Backports the TArray type to ARTIQ 5.
From @dnadlinger, this commit just exposes the internal TArray type to e.g. coredevice drivers.
I am backporting this for cross-version compatibility of DAX (Duke ARTIQ Extensions). 
This is pretty much the only blocker from it working with ARTIQ 5, so this minor backport makes sense.
ARTIQ tests pass with this backport.
N/A
|   | Type |
```
```
ARTIQ files that do not contain a license header are …
> [v5]: add TArray type

- artiq/test/test_tools.py
- artiq/tools.py
Use `SourceFileLoader` in `tools.file_import` to allow loading modules from files without the `.py` extension.
This is in particular useful when loading `device_db` from single-file Nix derivations.
Does this require an entry in the release notes?
|   | Type |
```
```
> tools/file_import: use SourceFileLoader

- artiq/firmware/libboard_misoc/lib.rs
- artiq/firmware/libboard_misoc/mmcspi.rs
- artiq/firmware/libboard_misoc/net_settings.rs
- artiq/gateware/targets/sayma_amc.py
Closes #1604.
* migen: https://github.com/m-labs/migen/pull/254
* openMMC: https://github.com/sinara-hw/openMMC/pull/3
> sayma: support MMC SPI & EUI48 reading

- RELEASE_NOTES.rst
- artiq/applets/big_number.py
- artiq/applets/image.py
- artiq/applets/plot_hist.py
- artiq/applets/plot_xy.py
- artiq/applets/plot_xy_hist.py
- artiq/applets/simple.py
- artiq/browser/datasets.py
- artiq/dashboard/datasets.py
- artiq/language/environment.py
- artiq/master/databases.py
- artiq/master/worker_db.py
- artiq/test/test_datasets.py
- artiq/test/test_scheduler.py
closes #1837 
DRAFT (needs check before merge)
> Revert "Merge pull request #1544 from airwoodix/dataset-compression"

- artiq/compiler/transforms/artiq_ir_generator.py
Although #1831 fixed some exception allocation issues by saving exception objects inside a buffer and avoid allocation for exceptions raised from an RPC, users can still call exception constructors with messages returned from an RPC, producing a dangling pointer in the exception object when the exception is raised. This patch prohibits users from doing this by only allowing static constant messages.
This will break some code that constructs exceptions with a function by passing the message as a parameter because we cannot know if the parameter is a constant. A way to mitigate this would be to defer this check to LLVM IR codegen stage, and do inlining first for those exception allocation functions, but I am not sure if we will guarantee inlining for certain functions, and whether this is …
> compiler: only allow constant exception messages

- artiq/compiler/transforms/artiq_ir_generator.py
- artiq/test/lit/try_loop/try_finally_while_try_finally_break.py
- artiq/test/lit/try_loop/try_finally_while_try_reraise.py
- artiq/test/lit/try_loop/try_finally_while_try_return.py
When we have a trys inside a loop then we want to make sure any
finallys are executed by break and continue inside this try. But
this shouldn't pull finallys defined outside the loop in to the
loop. This change resets the `outer_final` attribute when
visiting for and while loops so that this doesn't happen.
|   | Type |
The following experiments all execute successfully:
https://gist.github.com/mbirtwell/847339608f639f0d504fda352c70eb17 (this one failed to compile before)
https://gist.github.com/mbirtwell/9f9260afacd01b82ebe2cd2b1511e971
https://gist.github.com/mbirtwell/f5f5953474ab7b4fc168969ba3e367b6
```
```
See [copyright & licensing for …
> Fix try/finally:while:try compilation

- artiq/firmware/runtime/kern_hwreq.rs
Missed one when testing with a master configuration.
|   | Type |
> I2c switch fix for drtio

- artiq/coredevice/phaser.py
Add and delete the blank lines so that the incorrect formatting in the phaser doc pdf can be fixed.
Closes #1673 
|   | Type |
```
```
> fix the incorrect format in doc

- doc/manual/core_device.rst
Add the blank line between two lines so that the poor formatting of pdf can be changed.
Closes #1846 
|   | Type |
```
```
> Add the blank line to change the poor formatting of pdf

- artiq/dashboard/moninj.py
Signed-off-by: Laurent Stephenson <laurent.stephenson@nist.gov>
Make dashboard use the moninj proxy port from the `device_db` rather than hardcoding port 1383.
Closes #1890 
|   | Type |
Tested running dashboard with moninj port proxy set to non-default port in device_db, moninj working.
Changed port proxy value in device_db, updated with `artiq_client scan-devices`, moninj still working. 
```
```
> fix issue #1890: make dashboard use moninj port from device_db

- artiq/dashboard/datasets.py
Adding the rename dataset feature
Feature request: rename/move datasets in gui #1739 
|   | Type |
```
```
> create the rename dataset feature

- artiq/gui/entries.py
`KeyError: 'seed' `raised due to the missing key "seed" in "RangeScan" and "CenterScan"
Add item {"seed": None} in both "RangeScan" and "CenterScan" to solve the issue.
#1640 
|   | Type |
```
```
> Add the missing item in "RangeScan" and "CenterScan"

- artiq/applets/simple.py
- artiq/gui/applets.py
This allows ndscan v0.3+ to use the IPC interface for efficiency; previously, the non-upstreamed RID dataset namespace feature allowed the applets to somewhat efficient subscribe directly to the master process via the socket interface.
I briefly considered extending `datasets` by some sort of globbing syntax, but concluded that it's probably not worth the extra complexity…
> applets: Allow wildcard subscription to all datasets matching prefix via IPC

- artiq/coredevice/comm_moninj.py
- artiq/dashboard/moninj.py
- artiq/frontend/aqctl_moninj_proxy.py
- artiq/frontend/artiq_dashboard.py
Public the task in comm_moninj for the usage in proxy
Add log message when connected/reconnected
|   | Type |
```
```
> Disconnect Proxy after connection failure with core device

- artiq/frontend/artiq_master.py
- artiq/master/scheduler.py
- artiq/master/worker_impl.py
Add method that allows an experiment to check if termination has been requested.
Method to check if termination is requested #811 
|   | Type |
```
```
> Check termination

- artiq/frontend/artiq_flash.py
Make openocd exit when the scan chain is wrong in the script
artiq_flash: bail if scan chain is wrong #929 
|   | Type |
```
```
> Add exit in the script for the error of scan chain

- artiq/language/environment.py
test fail due to absent of `__argument_mgr`
fix by checking it
Result:
|   | Type |
```
```
> Bugfix: Failed test case in test_datasets

- artiq/gateware/drtio/transceiver/gtx_7series.py
Set DRTIO GTX clock buffer parameters
Some Kasli-SOC board's SFP connection may not work when clocked by ADCLK948 IC. 
Refer to 7 Series FPGAs GTX/GTH Transceivers User Guide (UG476) page 33-35 for rationale behind change.
|   | Type |
```
```
> Set DRTIO GTX clock buffer parameters

- artiq/dashboard/moninj.py
`AttributeError: 'list' object has no attribute 'keys' ` occur when Toggle DDS urukul0_ch0 off
Change from: `"arguments": []` to `"arguments": {}` to match the convention
|   | Type |
```
```
> moninj: Set "arguments" to dict

- artiq/gateware/targets/kasli.py
add Error LED to the Kasli's MasterBase and SatelliteBase submodule.
Test setup
1. Get a Kasli board
2. Insert a `panic!()` statement into the main function of files artiq/firmware/runtime/main.rs and artiq/firmware/satman/main.rs to simulate the rust firmware panic.
| before changes | after changes |
|---------------- | -----------------|
| Error LED Off | Error LED On |
Closes #1947 
|   | Type |
```
```
> Add Error LED to the Kasli's MasterBase and SatelliteBase submodule

- artiq/gateware/targets/kasli.py
Relocate Kasli's SatelliteBase Error LED code since the code does not belong with the transceiver clocking code.
#1952 
|   | Type |
```
```
> Relocate the Kasli's SatelliteBase Error LED code

- artiq/dashboard/moninj.py
Replace reset with break_realtime to the built-in experiment in the dashboard 
RTIO Underflow when setting DDS via ARTIQ Dashboard
|   | Type |
```
```
> Replace reset with break_realtime in the dashboard

- artiq/gui/log.py
Apply level and text filter to the log messages in panel
Incoming message filtering is removed
|   | Type |
```
```
> GUI log: Apply level and text filter to the log messages in panel

- artiq/examples/no_hardware/repository/custom_applet.py
`custom_applet.py` used in the `CreateCodeApplet` example needs to be updated with the latest constructor, `data_changed` signatures to work properly.
|   | Type |
+ basic test to ensure functionality
```
```
> custom_applet: change constructor, data_changed signatures

- doc/manual/conf.py
> doc: Mock platformdirs
