artiq/compiler/transforms/artiq_ir_generator.py
artiq/test/lit/integration/for.py
artiq/test/lit/integration/while.py

Previously, they would still target the respective labels in the
just-exited loop.

compiler: Fix break/continue targets in loop else blocks

---

artiq/compiler/transforms/llvm_ir_generator.py

Previously, the phi emitted for the pointer parameter to recv_rpc was –
rather confusingly – called "size", and the pseudo-code in the comment
had bit-rotted.

compiler: Clarify recv_rpc value names and documentation [nfc]

---

artiq/browser/experiments.py
artiq/dashboard/experiments.py
artiq/language/environment.py
artiq/master/worker_impl.py

This adds optional tooltips to experiment arguments in the Artiq Dashboard and Browser. 
This is useful as the ArgumentEditor gets unwieldy for long argument names - this allows one to use short argument names and add extra context as a tooltip.

Add tooltips to experiment arguments

---

artiq/monkey_patches.py

#506 / #508 appear again on Python 3.5.3 (see #670)

monkey-patch Python 3.5.3 asyncio.base_events._ipaddr_info

---

conda/artiq-dev/meta.yaml
conda/artiq/meta.yaml

The anaconda default anaconda pyqt (currently at 5.6.0) now works. 
If the m-labs pyqt5 package is installed alongside the anaconda pyqt package neither works - there are companion PRs to ensure m-labs/pyqtgraph and m-labs/quamash use the anaconda default pyqt. 
Tested on Windows and Linux: there are nothing obvious broken.

conda: use anaconda default pyqt (fixes #670)

---

artiq/master/worker_impl.py

The wall time when build() is called is currently recorded as the results key 'start_time'. 
This adds an additional key 'run_time', the time when run() is called.
This is useful for reconstructing experiment time-lines as the build time is often very different from the run time.

master: record time run() is called

---

artiq/protocols/pipe_ipc.py

#671 was not completely fixed by bd55436 - datasets > 4MB now crash out in pipe_ipc. 
This patch increases the line limit in pipe_ipc.

protocols: increase another asyncio line limit (#671)

---

RELEASE_NOTES.rst
artiq/master/log.py

Currently the master rotates logs based on file size, with numeric postfixes indicating the log age - this means that it is hard to determine which log file contains the output from a given experiment.
This patch changes the log rotation to occur at midnight. This means that after the log rolls over there is an easy to understand and immutable relationship between the experiment and the log file containing its output.

master: rotate logs at midnight, rather than on log size

---

RELEASE_NOTES.rst
artiq/master/worker_impl.py

Use time.time() for experiment run_time and start_time - the results directory names are still based on local time.

master: use epoch time for timestamps (closes #726)

---

RELEASE_NOTES.rst
artiq/frontend/artiq_dashboard.py
artiq/frontend/artiq_master.py

This PR implements two features which make Artiq more pleasant to use when connecting to multiple masters:
1) The dashboard config is (by default) stored separately for each different master, keyed by server address and port. This means that applets and experiment arguments don't mix between different masters.
2) The master can be labelled with a friendly name. If this is present, the dashboard displays this rather than the server address - this is particularly useful when connect to two masters on the same server (distinguished only by port).

Label masters with friendly name, store dashboard config per master (closes #848)

---

artiq/dashboard/experiments.py

When the user tried to open an experiment from the explorer that
already existed, previously "nothing would happen" (focus change
without the window being restored).

dashboard: Restore minimized experiments when trying to open them again

---

artiq/firmware/libboard/sdram.rs

Increases the initial delay step into the valid read window from 8 -> 16 as with the original delay I was not getting out of the noisy transition window, as evidenced by seeing read delay windows of only 8 LSB ~10% of the time, leading to failing memory tests.
See discussion on https://irclog.whitequark.org/m-labs/2018-01-11

firmware: make read leveling robust for KUS SDRAM

---

artiq/gateware/drtio/siphaser.py

correct documented siphaser VCO frequency [NFC]

---

artiq/firmware/libboard_artiq/hmc830_7043.rs
artiq/gateware/targets/sayma_rtm.py

Tested on my Sayma. Since implementing this fix, I haven't seen any more runtime crashes (although, serwb still seems unreliable on my board).
This requires the HMC7043 RESET line to be connected in hardware. My board had been reworked to short this to GND. NB connecting the HMC7043 RESET line breaks the Si5324 because they share a reset line.

Sayma RTM: hold hmc7043 in reset/mute state during init.

---

artiq/firmware/libboard_artiq/hmc830_7043.rs

We've seen several cases where noise on the HMC7043 outputs can disrupt the AMC FPGA in subtle ways -- even if there is no active logic clocked from them.
This PR disables all HMC7043 outputs that are not currently used to prevent them from causing problems.

Sayma: disable unused HMC7043 outputs

---

artiq/firmware/libboard_artiq/hmc830_7043.rs

- Break the HMC830 init into separate functions for general purpose (but, integer-N) init, setting dividers and checking lock
- Use 1.6mA ICP (which the loop filter was optimized for)
- Go through the data sheet carefully and set all registers to the correct value (e.g. ensure that all settings are correctly optimized for integer-N usage)
- Change divider values (now using 100MHz PFD, which should give lower noise in theory)
- Tested at Oxford and all locked reliably well here, but someone else should check this before merging!

Sayma HMC830: update interface and register writes.

---

doc/manual/installing.rst

The file 99-openocd.rules as downloaded from githubusercontent.com seems to be outdated and does not work on Ubuntu 16.04 (access error). The version that ships with OpenOCD has an additional ``TAG+="uaccess"`` in the rules file and works fine. Thus I suggest to use the file that is bundled with OpenOCD.

Update installing.rst to reflect changes in OpenOCD rules file

---

artiq/compiler/builtins.py

For instance, TTuple(TList(TInt32())) has indirections, while
TTuple(TInt32()) does not.
This fixes memory corruption with RPCs that return tuples of lists.
---
This is pretty much untested outside my one narrow application and would benefit from a test case, but I don't have time to be sidetracked by that right now.

compiler: Indirection status of TTuple depends on elements

---

artiq/master/worker_db.py

In larger experiments, it is quite natural for the same dataset
to be read from multiple unrelated components. The only situation
where multiple reads from an archived dataset are problematic is
when the valeu actually changes between reads. Hence, this commit
restricts the warning to the latter situation.

worker_db: Only warn on repeated archive read if dataset changed

---

artiq/coredevice/comm_moninj.py
artiq/dashboard/moninj.py
artiq/firmware/libproto_artiq/moninj_proto.rs
artiq/firmware/runtime/moninj.rs
artiq/test/coredevice/test_moninj.py

Previously if one dashboard overrode a channel this was not visible on any other dashboard - the channel appeared to operate under experiment control, and the actual output level was unrelated to the displayed output level.
This PR allows clients to be notified by the core device when the injection state is changed. With the current implementation the modifying client receives a notification of its change up to 200ms after the change, which means that the dashboard moninj panel cannot be used to generate events faster than 200ms.

share moninj injection state between dashboards

---

nix/README.rst
nix/artiq.nix
nix/binutils-or1k.nix
nix/default.nix
nix/fetch-llvm-clang.nix
nix/llvm-or1k.nix
nix/llvmlite.nix

Solution: Provide a single command to download, compile and install
dependencies.

Problem: ARTIQ setup via conda or src is complex

---

artiq/firmware/runtime/main.rs

This works around a problematic interaction between ARP cache
expiry in smoltcp (with its 3 seconds timeout before a discovery
request is sent) and our TCP keepalive settings, where the timeout
is reached before the keepalive had a chance to be sent.
GitHub: Closes #1150.

firmware: Use larger ARP cache

---

artiq/dashboard/moninj.py

Previously receiving an injection status callback for the TTL level set the displayed level, even if the channel was not overridden.

dashboard: fix TTL moninj level display

---

artiq/frontend/artiq_master.py
artiq/master/log.py
artiq/master/rid_counter.py
artiq/master/worker_db.py
artiq/master/worker_impl.py

More refactorings from back when I first looked at all this code and found it somewhat non-obvious which of all the similarly-named bits were used from which part of the stack. `RIDCounter` dind't fit with the rest, so I moved it out.

Clarify artiq.master.worker_{db, impl} separation

---

.github/ISSUE_TEMPLATE/1_Bug_Report.md
.github/ISSUE_TEMPLATE/2_Feature_Request.md
.github/ISSUE_TEMPLATE/3_Question.md
.github/pull_request_template.md

Add issue & pull request templates to make pull requests/issues more uniform when adding to Github, and provide suggested information to include in pull requests/issues.
These will autopopulate on Github. Based on `pylint` templates.

Add issue & pull request templates

---

RELEASE_NOTES.rst
artiq/coredevice/core.py
artiq/coredevice/ttl.py
artiq/examples/kasli_basic/repository/kasli_tester.py
artiq/examples/kc705_nist_clock/repository/photon_histogram.py
artiq/examples/kc705_nist_clock/repository/tdr.py
artiq/examples/no_hardware/repository/al_spectroscopy.py
artiq/language/core.py
artiq/sim/devices.py
artiq/test/coredevice/test_analyzer.py
artiq/test/coredevice/test_rtio.py
doc/manual/rtio.rst
doc/slides/artiq_overview.tex
doc/slides/taaccs.tex

The motivation behind this change is that the current API doesn't play well with DMA as detailed in #1113 – RTIO events generated by DMA can't set the timestamp attributes.
The only part of the change strictly necessary to fix this are the optional timestamp arguments, so that code using DMA can manually specify these. However, as pointed out in #1113, the current API is unnecessarily error-prone, especially as DMA is deployed more and more widely (and possibly hidden behind layers of abstraction).
Hence, I removed `TTLOut.sync` altogether, since it seems to be used only very rarely (there are zero uses in `artiq`, as well as all our experiment code). The input methods, on the other hand, are used much more often, so 67fe87a makes them default to `now_mu()` when no timestamps are passed …

ttl: Stop tracking function call cursor positions

---

artiq/firmware/ksupport/lib.rs

Tested locally on the actual application, but there don't seem to be any tests for wide-output DMA @sbourdeauducq / @whitequark: Did I miss a place where an integration test could easily be added?

firmware: Fix dma_record_output_wide

---

artiq/gui/entries.py
artiq/language/scan.py

* parametrized by center/span/step instead of
start/stop/npoints which is more convenient in some applications
* no scan widget support so far
Signed-off-by: Robert Jördens <rj@quartiq.de>
|   | Type |
```
```

gui,scan: add CenterScan Scannable variant

---

artiq/frontend/artiq_flash.py

Added `clear` command to `artiq_flash` to erase flash memory
Sometimes after flashing kasli or sayma for the n-th time ARTIQ won't boot. Usually clearing flash memory helps with this problem, so I added an option to do this from `artiq_flash`. Tested on Kasli v1.1.
|   | Type |
```
```

Added clear command to artiq_flash to erase flash memory

---

artiq/examples/kasli_basic/repository/kasli_tester.py

Add Windows platform support to kasli_tester.py
None
|   | Type |
None
```
```

kasli: add support for windows platform.

---

artiq/examples/kc705_nist_clock/repository/tdr.py

Misspelling in TDR example

---

artiq/coredevice/ad9910.py
artiq/coredevice/spi2.py

Warnings thrown while building docs. Forgot to rename some attributes, and a bad indent in spi2 docstring.
Signed-off-by: Drew Risinger <drewrisinger@users.noreply.github.com>

Docs: fix build warnings

---

artiq/examples/kasli_sawgmaster/repository/sines_2sayma.py
artiq/examples/kasli_sawgmaster/repository/sines_urukul_sayma.py
artiq/examples/sayma_masterdac/repository/sines_drtio.py

Using the default routing table, links numbers and destinations are offset by 1, as destination 0 is local RTIO. Hence, code previously using `get_drtio_link_status` needs updating.
Not tested yet.
@sbourdeauducq: As discussed.

examples: Fix DRTIO destination indices

---

artiq/frontend/artiq_influxdb.py

Make names of argparse group variables relate to what they're doing.
Meets Flake8.
Signed-off-by: Drew Risinger <drewrisinger@users.noreply.github.com>

Influxdb: clarify argparse groups

---

artiq/protocols/pc_rpc.py
artiq/test/test_pc_rpc.py

Change how `pc_rpc` process annotations. Essentially `annotations -> str(annotations)` which can be serialized by `pyon`.
Closes #1186 
|   | Type |
- Added unittest to check this. Manually tested as well with `artiq_rpctool SERVER list-methods`
None

Fix #1186: list-methods of type-annotated class

---

artiq/test/test_pc_rpc.py

Fixes bug from 5108ed8. Truth value of multi-element numpy array is
not defined. Completes #1186 and fixes/amends #1188.
Signed-off-by: Drew Risinger <drewrisinger@users.noreply.github.com>

test_pc_rpc: fix equality bug (#1188)

---

artiq/master/databases.py
artiq/master/experiments.py
artiq/master/scheduler.py
artiq/master/worker_db.py
artiq/protocols/sync_struct.py
artiq/test/test_pc_rpc.py
artiq/test/test_sync_struct.py

These are some refactorings from back when I first looked at sync_struct and related code, lumped together into one PR for CI testing – see individual commits for details.
The only potentially contentious change is the renaming of `Notifier.read`, which I always found difficult to make sense of – Is it a property that `read()`s in new data? Or the previously read data? Etc. Alternative bikeshed colour suggestions welcome.

Various sync_struct refactors

---

artiq/master/scheduler.py
artiq/master/worker.py
artiq/test/test_scheduler.py

This is just to CI-test a few uncontroversial changes and get them out of the way before a larger imminent PR to extend the scheduler (support for idling experiments that yield to lower-priority runs).

scheduler: Add shutdown test, minor refactors

---

artiq/gateware/rtio/phy/servo.py

Signed-off-by: Thomas Harty <thomas.harty@physics.ox.ac.uk>
Fix writing of SU-Servo coefficient data.
c.f. #1258
|   | Type |
The following test fails on Artiq 5 for a few reasons. This commit fixes one of the causes.
```python
import numpy.random as rand
from artiq.coredevice.suservo import COEFF_WIDTH
class Startup(EnvExperiment):
self.setattr_device("aom_servo")
self.setattr_device("aom_397_doppler")
self.offset = -0.00817
def run(self):
coeff_max = 1 << COEFF_WIDTH - 1
self.ftw = self.pow_ = self.offs = 0
for i in range(1000):
self.a1 = rand.randint(low=-coeff_max, high=coeff_max)
self.b1 = rand.randint(low=-coeff_max, high=coeff_max)
self.b0 = …
```

suservo: fix coefficient data writing

---

artiq/coredevice/suservo.py

I believe this parameter was used in a previous version of the servo, but has since been removed.

SUServo: remove references to non-existent a0 parameter

---

artiq/coredevice/suservo.py

Signed-off-by: TPH <thomas.harty@physics.ox.ac.uk>
The MSB of the RTIO data are now used to extend the servo's address space beyond the 8 bits provided by RTIO. In the current code, writing values with bits above `COEFF_WIDTH` set corrupts the address. This commit masks of the MSB of value to prevent this.
cf https://github.com/m-labs/artiq/pull/1259 (NB 9f9beb4a5935a43f718efa64c75702863f819acf also masks off the MSB of FTW writes which is, AFAICT, redundant).
Closes #1258
|   | Type |
```
```
ARTIQ files that do not …

SUServo: apply bit masks to servo memory writes to prevent overflows

---

RELEASE_NOTES.rst
artiq/frontend/artiq_influxdb.py
artiq/language/environment.py
artiq/master/worker_db.py
artiq/test/test_datasets.py

This adds `HasEnvironment.append_to_dataset()` for (efficiently) appending to datasets from experiment code.
All the required `sync_struct` machinery is already in place; appending just wasn't exposed previously.
Also adds some unit tests; the dataset API was largely untested before.

language: Support appending to datasets

---

conda/artiq-dev/meta.yaml

Per @vmsch, the Sayma targets apparently don't build with the mi{gen, soc} versions pulled in by the `artiq-dev` conda metapackage. This updates the version references to the latest commits, fixing the build.

conda: Bump migen/misoc commits to fix Sayma build

---

doc/manual/rtio.rst

In `doc/manual/rtio.rst` make wavedrom extension arguments strict JSON, as required by sphinxcontrib-wavedrom-2.0.0 (the JSON being parsed with Python, not eval'ed in the browser). Change is backwards compatible to sphinxcontrib-wavedrom-1.3.1.
(To appear in nix-scripts/)
|   | Type |

manual: fix wavedrom extension json syntax

---

artiq/dashboard/moninj.py

With growing system complexity, the moninj channel index is no longer a very intuitive ordering for typical end users.
@sbourdeauducq: Okay to merge? I could add a context menu option to switch between orders instead, but from our experience, there really isn't a use case for ordering by channel index.

dashboard: Sort TTL moninj channels by name

---

RELEASE_NOTES.rst
artiq/dashboard/experiments.py
artiq/language/environment.py
artiq/master/experiments.py
artiq/master/worker.py
artiq/master/worker_impl.py

Add methods callable from experiment build() to set pipeline/priority/flush defaults.
Suggestions on a cleaner way of indicating the functionality of the "recompute scheduler options" button without bloating the GUI appreciated.
Closes #692
|   | Type |

Add methods to set experiment pipeline/priority/flush defaults

---

artiq/test/coredevice/test_portability.py
artiq/test/hardware_testbench.py

Hardware tests now pass, apart from a separate regression from the recent AD9910 driver work:
```
======================================================================
ERROR: test_sync_window (test_ad9910.AD9910Test)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/cjbe/artiq/artiq/test/coredevice/test_ad9910.py", line 342, in test_sync_window
self.execute(AD9910Exp, "sync_window")
File "/home/cjbe/artiq/artiq/test/hardware_testbench.py", line 137, in execute
raise error from None
File "/home/cjbe/artiq/artiq/test/hardware_testbench.py", line 132, in execute
exp.run()
File "/home/cjbe/artiq/artiq/test/coredevice/test_ad9910.py", line 17, in run
getattr(self, self.runner)()
File "/home/cjbe/artiq/artiq/language/core.py", …
```

tests: fix coredevice tests after implementing scheduler defaults

---

artiq/gateware/targets/kasli.py

Only add moninj core to Kasli standalone/master/satellite base classes if there are moninj probes to monitor.
Fixes #1202

kasli: only add moninj core if there are probes to monitor

---

artiq/compiler/embedding.py
artiq/compiler/transforms/llvm_ir_generator.py
artiq/test/lit/embedding/tuple.py

Previously, they would end up being TInstances, rendering them rather useless.
@whitequark: Am I missing something here that would make this undesirable in the general case, or was this just an oversight?
If we were worried about codegen for tuples with a lot of elements, we could emit a reference to a global constant instead.

compiler: Quote tuples as TTuple values

---

artiq/protocols/sync_struct.py

sync_struct: replace ConnectionError sub-classes with ConnectionError

sync_struct: replace ConnectionError subclasses with ConnectionError

---

artiq/protocols/sync_struct.py

sync_struct: catch connection errors raised in _receive_cr

sync_struct: catch ConnectionErrors in _receive_cr

---

artiq/coredevice/suservo.py

Y0 is 18 bit signed, so the code (correctly) used 2^17 for the scale factor. The maximum representable number is 2^17 - 1, though, so `Channel.set_y(1.0)` would overflow to negative full scale instead.

coredevice/suservo: Fix {get,set}_y_mu() scaling

---

RELEASE_NOTES.rst
artiq/firmware/libboard_artiq/i2c.rs
artiq/firmware/libboard_artiq/i2c_eeprom.rs
artiq/firmware/libboard_artiq/lib.rs
artiq/firmware/libboard_artiq/pca9548.rs
artiq/firmware/libboard_artiq/si5324.rs
artiq/firmware/runtime/main.rs

* New firmware driver for the I2C EEPROM on Kasli
* The EEPROM contains a unique EUI-48 identifier that is used as the default Ethernet address.
Closes #955 
|   | Type |

Kasli: default Ethernet address from I2C EEPROM

---

artiq/firmware/libboard_artiq/lib.rs

Fixes conditional compilation of the pca9548 module.
Fix for [build failure of artiq-board-metlino-master](https://nixbld.m-labs.hk/build/11703/nixlog/1).
|   | Type |

firmware: fix conditional compilation of pca9548

---

artiq/firmware/runtime/kern_hwreq.rs

PR #1351 modified the return type of i2c functions. This must be done for remote_i2c as well.
From what I grepped no further other code is affected by these signature changes?
This should resolve breakage on a few targets/variants introduced by PR #1351.
|   | Type |

firmware: turn errors into &str for remote_i2c as well

---

artiq/frontend/artiq_influxdb_schedule.py

|   | Type |
Very simple tweak to log `repo_rev` to InfluxDB as a tag, via `artiq_influx_schedule`.

influx_schedule: log repo_rev along with other info

---

artiq/master/worker_impl.py

Accept experiment docstrings that start with a newline. 
|   | Type |
PEP 257 suggests valid multiline docstrings can start with a newline: support this syntax.

worker_impy: ignore newline at start of experiment docstring

---

artiq/coredevice/ad9910.py

RAM mode amplitude to ASF conversion should be `<< 18` rather than `<< 16` when in `RAM_DEST_ASF` mode.
page 33
https://www.analog.com/media/en/technical-documentation/data-sheets/AD9910.pdf

Fix ad9910 ram mode asf scale error

---

artiq/gateware/eem.py

Without this, the final register in the SYNC signal TTLClockGen
isn't (always) placed in the I/O tile, leading to more jitter
than necessary, and causing "double window" artefacts. See
sinara-hw/Urukul#16 for more details.
(Patch based on work by Weida Zhang, testing by various members
of the community in Oxford and elsewhere.)
---
@jordens: Over on the Urukul issue, you mentioned:
> We generally expect the toolchain to pack these registers. I'd be surprised if it didn't here. If it didn't we should find out and check all similar cases (e.g. TTL I/O or SPI clocks) where we assume packing.
Given that this definitely changes behaviour on the Urukul SYNC clock, are there any other signals we should pin like this right away?

gateware/eem: Force IOB=TRUE on Urukul SYNC output

---

artiq/coredevice/ad9910.py

Function set_asf() in class AD9910 should contain <<2, as per ASF register documentation on p. 58 of https://www.analog.com/media/en/technical-documentation/data-sheets/AD9910.pdf.
Updated docstrings for several functions in class AD9910.
|   | Type |

Update for AD9910 ram mode

---

artiq/gateware/eem.py
artiq/gateware/suservo/pads.py
artiq/gateware/targets/kasli_generic.py

implemented by wiring up the second Urukul to dummy pins
tested on bonn1master/bonn1satellite
Signed-off-by: Robert Jördens <rj@quartiq.de>
#1339 for more than two Urukul
|   | Type |
- [n/a] Update [RELEASE_NOTES.md](../RELEASE_NOTES.md) if there are noteworthy changes, especially if there are changes to existing APIs.
- [n/a] Close/update issues.
- [n/a] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).
```
``` …

suservo: support operating with one urukul

---

artiq/firmware/libboard_artiq/hmc830_7043.rs

Signed-off-by: Paweł Kulik <pawel.kulik@creotech.pl>
Without setting driver impedance there is no signal on SYSREF outputs. [Figure 20.](https://datasheet.octopart.com/HMC7043LP7FETR-Analog-Devices-datasheet-62096689.pdf#%5B%7B%22num%22%3A33%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C54%2C714%2Cnull%5D) suggests that we should enable internal 100 Ohms when using DC coupling and no external pullups (altough it's not clear to me what they had in mind in this documentation). I checked that ARTIQ now progresses past "DAC sync failed: no sync lock" + that there is a clean clock on SYSREF intputs with 1Vpp swing. Before that change there was no signal and 0V at sysref signals.
|   | Type | …

Enabled internal pullup for CML SYSREF outputs, otherwise there is no signal on them.

---

artiq/frontend/artiq_flash.py

Added `rtm_gateware` option to `artiq_flash`, which flashes only RTM gateware on Sayma AMC variants with RTM. It makes debugging RTM faster.
|   | Type |

Added option of flashing only RTM gateware.

---

artiq/compiler/embedding.py
artiq/language/core.py
artiq/test/lit/embedding/eval.py

With support for polymorphism (or type erasure on pointers to
member functions) being absent in the ARTIQ compiler, code
generation is vital to be able to implement abstractions that
work with user-provided lists/trees of objects with uniform
interfaces (e.g. a common base class, or duck typing), but
different concrete types.
`@kernel_from_string` has been in production use for exactly
this use case in Oxford for the better part of a year now
(various places in ndscan).
I do realize that part of the current use case might be
obsoleted by future extensions to ARTIQ Python (see discussion
in #1089), but generating source code will likely always have a
small place to fill in some gaps between the richness of Python
and the restrictions of kernel code. The (intentionally) restrictive …

compiler, language: Implement @kernel_from_string

---

artiq/compiler/embedding.py
artiq/test/lit/embedding/annotation.py
artiq/test/lit/embedding/error_specialized_annot.py

Similar to how Python itself interprets `None` as `type(None)`,
make it translate to `TNone` in ARTIQ compiler type hints.
We have somewhat unintentionally been running with this change
locally for a long time, and (certainly without me realising) ended up
with `None` being used all over our code base – it seems like this
syntax comes naturally to users without much thought.
(Passes artiq-fast build tests, this time.)

compiler: Allow `None` in type hints

---

artiq/compiler/types.py

These two commits improve the total compile time (artiq_run invocation to start of kernel upload) in one typical experiment by ~17%.
---
@whitequark: I'm putting this up as a PR just in case you have any ideas to reduce the number of identity `unify()` calls altogether. From a quick look, there doesn't seem to be a pathological cause for those, though.

compiler: Improve type inference performance by identity checks/early returns

---

artiq/coredevice/adf5355.py
artiq/coredevice/mirny.py
artiq/frontend/artiq_ddb_template.py
artiq/gateware/eem.py
artiq/gateware/targets/kasli_generic.py
doc/manual/core_drivers_reference.rst

* This targets the CPLD gateware at https://github.com/quartiq/mirny
* includes initial coredevice driver, eem shims, and kasli_generic tooling
* addresses the ARTIQ side of #1130
* Register abstraction to be written
Test report from @airwoodix:
- on a fresh power-up, it needs two tries to lock (artiq_run twice);
- the MUXOUT=DVDD check in ADF5355.init fails randomly when
manipulating reg1. It might be a delay thing, haven't investigated
systematically yet;
- the clk_sel documentation in the gateware code seems wrong to
me. The schematics has in_sel0 and in_sel1 exchanged. The easiest
might be to exchange the pins in the platform description.
Closes #1130
|   | Type |
| ✓ …

[WIP] mirny: add

---

artiq/gateware/targets/kasli_generic.py

This PR cherry-picks the fix to #1403 into the release-5 branch

kasli_generic(ARTIQ5): expose peripheral_processors

---

artiq/remoting.py

Added option of specifying another username when connecting through SSH (using `username@server`)
|   | Type |
Tested if I can connect both with and without specifying username.

Added option of specifying another username when connecting through SSH.

---

artiq/language/environment.py
artiq/test/test_arguments.py

Cast/process default values of argument processors in the initialization method explicitly. Also adds some unit tests for `NumberValue`, `BooleanValue`, and `EnumerationValue`.
Decision points:
Closes #1434 
|   | Type |
```
```

Cast argument processor default values early

---

RELEASE_NOTES.rst
artiq/gateware/rtio/phy/ttl_serdes_generic.py

Edges on pulses shorter than the RTIO period were missed because the
reference sample and the last sample of the serdes word are the same.
This change enables detection of edges on pulses as short as the
serdes UI (and shorter as long as the pulse still hits a serdes sample
aperture).
In any RTIO period, only the leading event corresponding to the first
edge with slope according to sensitivity is registerd. If the channel is
sensitive to both rising and falling edges and if the pulse is contained
within an RTIO period, or if it is sensitive only to one edge slope and
there are multiple pulses in an RTIO period, only the leading event is
seen. Thus this possibility of lost events is still there. Only the
conditions under which loss occurs are reduced.
In testing with the kasli-ptb6 …

ttl_serdes: detect edges on short pulses

---

RELEASE_NOTES.rst
artiq/coredevice/ad53xx.py

*  Input validation has been added to voltage_to_mu(). (closes #1444)
*  Documentation improvements
* State valid voltage range (closes #1443)
* Conversion is only valid for 16-bit members of the family
*  Make `voltage_to_mu()` availible as a `statimethod`. The exising function is maintained for backwads compatibility, but is also exposed as a `staticmethod` of `AD53xx`. (closes #1341)
|   | Type |
|  | :bug: Bug fix  |
*  Called voltage_to_mu via zotino and imports (both in and outside kernel)
*  Verified that exception is rasied on over/underflow
There seem to be no Zotino tests. …

ad53xx improvements

---

RELEASE_NOTES.rst
artiq/coredevice/ad9910.py

The ASF is a 14-bit word. The highest possible value is 0x3fff, not
0x3ffe. `int(round(1.0 * 0x3fff)) == 0x3fff`.
I don't remember and understand why this was 0x3ffe since the beginning.
0x3fff was already used as a default in `set_mu()`
Signed-off-by: Robert Jördens <rj@quartiq.de>
|   | Type |
```
```

ad9910: fix asf range

---

artiq/coredevice/ad9912.py

FTW and phase word were ambiguously typed, resulting in failure to compile for Experiments using the AD9912. 
See discussion in #1463

ad9912: Fix typing problem on ad9912

---

RELEASE_NOTES.rst
artiq/master/scheduler.py
artiq/master/worker.py
artiq/master/worker_impl.py

Previously, a significant risk of losing experimental results would
be associated with long-running experiments, as any stray exceptions
while run()ing the experiment – for instance, due to infrequent
network glitches or hardware reliability issue – would cause no
HDF5 file to be written. This was especially troublesome as long
experiments would suffer from a higher probability of unanticipated
failures, while at the same time being more costly to re-take in
terms of wall-clock time.
Unanticipated uncaught exceptions like that were enough of an issue
that several Oxford codebases had come up with their own half-baked
mitigation strategies, from swallowing all exceptions in run() by
convention, to always broadcasting all results to uniquely named
datasets such that the partial results …

master: Always write results to HDF5 once run stage is reached

---

RELEASE_NOTES.rst
artiq/dashboard/experiments.py
artiq/gui/fuzzy_select.py

This is similar to functionality in Sublime Text, VS Code, etc.
---
This is part of my effort to reduce our (Oxford) upstream diff. We've been using something like this for a long time, and most people seem to find it to be a convenient addition (although the code did go through a bit of cleanup before submitting this). Using a QMenu for displaying the choices might seem a bit odd, but in the absence of a completely custom widget to combine text box and choices into one modal dialog, works quite well on Windows, Mac and Linux.
This is used for choosing parameter overrides in ndscan as well (although currently through a local copy).

dashboard: Add "Quick Open" dialog for experiments on global shortcut

---

RELEASE_NOTES.rst
artiq/firmware/runtime/main.rs

Before, the system would enter a boot loop when a panic occurred
while the kernel CPU was active (and panic_reset == 1), as
kernel::start() for the startup kernel would panic.

runtime: Stop kernel CPU before restarting comms CPU on panic

---

artiq/firmware/libboard_misoc/i2c.rs

Duplicate control byte in I<sup>2</sup>C, in accordance with "7. Parameter Measurement Information" in the [TCA9548 datasheet](https://www.ti.com/lit/ds/symlink/tca9548a.pdf?ts=1593747422231&ref_url=https%253A%252F%252Fwww.google.com%252F)

I2C: Duplicate TCA9548 control byte

---

artiq/firmware/libboard_misoc/i2c.rs

* Never drive SDL or SDA high. They are specified to be open
collector/drain and pulled up by resistive pullups. Driving
high fails miserably in a multi-master topology (e.g. with
a USB I2C interface). It would only ever be implemented to
speed up the bus actively but that's tricky and completely
unnecessary here.
* Make the handover states between the I2C protocol phases (start, stop,
restart, write, read) well defined. Add comments stressing those
pre/postconditions.
* Add checks for SDA arbitration failures and stuck SCL.
* Remove wrong, misleading or redundant comments.
|   | Type |
|    | :sparkles: New feature |
```
Longer …
```

firmware/i2c: rewrite I2C implementation

---

RELEASE_NOTES.rst
artiq/language/environment.py

Allow forcing a NumberValue to return a float by passing `force_float=True`, even if other conditions (i.e. `ndecimals=0`, `scale=1` and `step` is integer) would allow it to be an integer. 
|   | Type |

parameters: Allow forcing a NumberValue to return a float

---

RELEASE_NOTES.rst
artiq/coredevice/comm_kernel.py
artiq/firmware/libproto_artiq/lib.rs
artiq/firmware/libproto_artiq/rpc_proto.rs
artiq/test/coredevice/test_performance.py

Optimized performance for RPC list and array transfer of primitive types. Added some more tests for performance of RPC.
Tested on kc705 and zynq platform with `test_performance`, `test_embedding` and `test_numpy`. No regression.
- Lists/arrays with non-primitive types (not Bool/Int32/Int64/Float) are not optimized that well and are in general hard to optimize well.
- This patch changes the RPC protocol for list and array, users should ensure they have the same firmware and compiler version.
- The performance test would no longer assert the data correctness. Use `test_embedding` and `test_numpy` for correctness check.
- The performance test now uses normal RPC instead of async RPC now, as this could better represent the actual throughput, and async RPC cannot be used to test for …

RPC Performance Optimization

---

artiq/coredevice/comm_kernel.py
artiq/test/coredevice/test_performance.py

RPC performance optimization for Python code. This patch reduces the number of calls to socket functions, thus hope to improve the throughput for small but more complex RPCs.
This patch also added some tests for small RPC calls, and print a table for performance test summary.
Each test is run for 10 times. H2D means host to device, D2H means device to host.
artiq-zynq:
| Test                 | Mean before (MiB/s) |  std before (MiB/s) | Mean after (MiB/s) |  std after (MiB/s) | Mean Diff  |
| -------------------- | ------------: | ------------: | ------------: | ------------: | -------: |
| I32 Array (1MB) H2D  |        40.77 |         2.73 |        38.51 |         3.13 | -5.54% |
| I32 Array (1MB) D2H  |        28.77 |         2.51 |        32.24 |         0.65 | 12.06% |
| I32 Array …

RPC Performance Optimization Take 2

---

artiq/examples/metlino_sayma_ttl/device_db.py
artiq/examples/metlino_sayma_ttl/repository/demo.py
artiq/gateware/fmcdio_vhdci_eem.py
artiq/gateware/targets/sayma_amc.py

This adds Sayma's gateware support as a satellite controlling 2 DIO cards via an FMC-VHDCI-LVDS adaptor. This is demonstrated with an example containing a Metlino master and Sayma satellite.
The modification of Sayma RTL is to import the existing RTL library for the FMC-VHDCI-LVDS. A minor error in the library has been fixed.
The additional ARTIQ example was created based on `artiq_sinara_tester`. However, it is worth noting that certain functions originally from Sinara tester that does not run in the kernel need to be run in the kernel, as per testing. This might be due to how the list of LED and TTL devices gets initialised in my script, which might have differences from Sinara tester which I have overlooked. Nevertheless, this example suffice the requirement of demonstrating the TTL …

metlino_sayma_ttl: Example of Metlino-master, Sayma-satellite system

---

artiq/build_soc.py

Actually, we want to override the identifier_str just for the gateware but not the for the firmware.
This fixes the `software ident` output. Should we change the arg into `gateware_identifier_str` in all callers for more clarity?

build_soc: override identifier_str only for gateware

---

artiq/build_soc.py

build_soc: remove assertion that was used for test runs

---

artiq/compiler/transforms/artiq_ir_generator.py

Fixes incorrect behavior for with statements with multiple items.
It seems that the lambda expression is lazily evaluated, and the exit function that it binds to changes to the one of the last item.
Closes #1478
|   | Type |
```
```

fixes with statement with multiple items

---

artiq/compiler/transforms/artiq_ir_generator.py

Fixes none to bool coercion.
Closes #1413, #1414
|   | Type |
```
```

Fixes none to bool coercion

---

artiq/compiler/transforms/artiq_ir_generator.py
artiq/test/lit/codegen/custom_comparison.py
artiq/test/lit/codegen/custom_inclusion.py

Added error messages for object comparison, instead of assert fail.
Example output:
```
eq.py:16:16-16:35: error: Custom object comparison is not supported
return self.bar > self.baz
^^^^^^^^^^^^^^^^^^^^
eq.py:16:16-16:36: error: Custom object comparison is not supported
return self.bar == self.baz
^^^^^^^^^^^^^^^^^^^^
```
Closes #1396.
|   | Type |
```
```

compiler: added error message for object comparison

---

artiq/compiler/module.py
artiq/compiler/targets.py
artiq/compiler/transforms/artiq_ir_generator.py
artiq/coredevice/core.py
artiq/coredevice/exceptions.py
artiq/test/coredevice/test_embedding.py
artiq/test/lit/integration/instance.py

This allows assert() to be used on Zynq, where abort() is not
currently implemented for kernels. Furthermore, this is arguably
the more natural implementation of assertions on all kernel targets
(i.e. where embedding into host Python is used), as this way, the
exception information actually makes it to the user.
Since this does not implement printing of the subexpressions, I
left the old print+abort implementation as default for the time
being.
GitHub: Fixes #1539.
---
Needs testing still. (Even if Zynq was the specific motivation here, I've wanted something like this for a while, as assert()s are phenomenally undebuggable with core log forwarding as unreliable as it currently is.)

compiler: Raise exception on failed assert()s rather than panic

---

artiq/gui/entries.py

Fixed a bug in the center scan widget that causes scaling to be applied twice.
Fix applies both to master and release-5 branch, I would like to have the patch on the release-5 branch.
No related issues.
|   | Type |
Changes too small to affect the points below.
Changes too small to affect the points below.
```
```

fixed value scaling issue for the center scan gui widget

---

artiq/coredevice/ad9910.py

When run on the host, the 16-bit word from `turns_to_pow` retruns a `numpy.int64`. Meanwhile, all other machine unit return types of the ad9910 are the more appropreate `numpy.int32`. 
Sensibly, the compiler does not attempt to convert `numpy.int64` to `int32`. These bahaviours combine to give compiler errors when attempting to cache the machine unit parameters in a list, as mixed-type lists are not supported. Currently this needs to be worked around by casting the pow to `numpy.int32`.
This behaviour will also occur for ad9912. However, I do not have the hardware to test this fix on an ad9912. In light of #1463 and #1468 it seems unwise to modify this without testing on hardware.
|   | Type |
|  | :sparkles: New feature |
|  | …

ad9910: fix `turns_to_pow` return-type on host

---

artiq/compiler/prelude.py

closes #1477
The ARTIQ compiler buildins describe the `RuntimeError`, but it was never added to the global environment of the kernel. This small fix adds the line that was probably forgotten earlier. Now a `RuntimeError` can be raised from kernels.
This fix also applies to the master branch, but I would also like to have it on the release-5 branch.
Closes #1477
|   | Type |
```
```
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and …

Added RuntimeError to prelude to make the name available in kernels

---

artiq/dashboard/moninj.py

When the dashboard can not connect to the core device for moninj, the window of the dashboard can not be closed. This fix breaks that infinite try-to-connect loop in case the user wants to close the dashboard window.
It seems that this fix would also apply to the master branch, but I would also prefer to have it in release-5.
I don't think there are specific issues for this small bug.
|   | Type |
```
```
ARTIQ files that do not contain a license header are …

allow dashboard to close if no connection can be made to moninj

---

artiq/frontend/artiq_ddb_template.py

The following changes complement #1530.
- Rename ADF5355 to ADF5356 in `artiq_ddb_template.py`.
- Propagate `clk_sel`, `refclk` arguments from JSON file to `device_db.py`.
A JSON snippet with the following Mirny v1.1 configuration created.
```json
{
"type": "mirny",
"ports": [8],
"clk_sel": 1
},
```
`artiq_ddb_template.py` then generates the following Mirny entries in `device_db.py`.
```python
device_db["spi_mirny0"]={
"type": "local",
"module": "artiq.coredevice.spi2",
"class": "SPIMaster",
"arguments": {"channel": 0x01001f}
}
device_db["ttl_mirny0_sw0"] = {
"type": "local",
"module": "artiq.coredevice.ttl",
"class": "TTLOut",
"arguments": {"channel": 0x010020}
}
device_db["ttl_mirny0_sw1"] = {
"type": "local",
"module": "artiq.coredevice.ttl",
"class": "TTLOut",
"arguments": {"channel": …
```

artiq_ddb_template: Rename adf5355 to adf5356, add Mirny CPLD arguments

---

.github/pull_request_template.md

Signed-off-by: Aadit Rahul Kamat <aadit.k12@gmail.com>
Changed the link to Release Notes document from `../RELEASE_NOTES.md` to `../RELEASE_NOTES.rst` in the PR template.

Update link to Release Notes doc in PR template

---

artiq/gateware/jesd204_tools.py
artiq/gateware/targets/sayma_amc.py

This is to make the Sayma satellite code on `master`, which is running at an RTIO frequency of 150 MHz and DAC rate of 600 MS/s (with 4x interpolation), adapt to a proposed renewal of our [JESD204B core](https://github.com/m-labs/jesd204b) (PR: https://github.com/m-labs/jesd204b/pull/14), which has introduced new syntax for instantiating GTH transceivers.
In general, all changes for `jesd204_tools` in this PR are compatible with all kinds of target line rates (corresponding to either CPLL or QPLL defined by Xilinx). In the file, the only lines that needs to be changed for different JESD settings are [63-65](https://github.com/m-labs/artiq/blob/eac5d5fc8cf5efb39a5f6f5ffda4ce6e62a20531/artiq/gateware/jesd204_tools.py#L63-L65).

sayma: Rewrite JESD code with renewed JESD core

---

artiq/firmware/libboard_artiq/ad9154.rs
artiq/firmware/satman/jdcg.rs
artiq/firmware/satman/main.rs
artiq/gateware/jesd204_tools.py
artiq/gateware/targets/sayma_amc.py

This is to make the Sayma satellite code on `sayma1g`, which runs at an RTIO frequency of 125 MHz and DAC rate of 1000 MS/s (with 2x interpolation), adapt to a proposed renewal of our [JESD204B core](https://github.com/m-labs/jesd204b) (PR: https://github.com/m-labs/jesd204b/pull/14), which has introduced new syntax for instantiating GTH transceivers. For a similar PR for adapting RTIO@150MHz to the renewed JESD core, see: https://github.com/m-labs/artiq/pull/1568
For `artiq/gateware/jesd204_tools.py`, comparing this PR with #1568, the JESD settings has been slightly adjusted: K (number of frames per multiframe) has been doubled to 32. Testing has shown that with K=16, the JESD core would often report not ready. With K=32, this issue never occurs.
Other minor changes include:
* Perform …

sayma: Implement 1 GS/s with renewed JESD core

---

artiq/firmware/runtime/main.rs
artiq/firmware/satman/main.rs

#1570 was caused by the same problem as #1508, in that the SFP1..3 TX_DISABLE lines were not driven low, and hence the SFP transmit was disabled.
This patch has been tested on a pair of Kasli 2.0, using all possible downstream ports on the master Kasli.

kasli v2.0: drive TX_DISABLE low on all SFPs (fixes #1570)

---

artiq/coredevice/comm_kernel.py
artiq/coredevice/core.py

Use device endian for kernel and RPC protocol. 
Note: This breaks the protocol for artiq-zynq, users must update the zynq firmware after this change.
This improves the performance of integer array transfer for zynq. For large integer array transfer, the throughput difference:
| Test                 | Prev (MiB/s) | Now (MiB/s)  |  Diff  |
| -------------------- | ------------ | ------------ | ------ |
| I32 Array (1MB) H2D  |        44.08 |        47.47 | +7.69% |
| I32 Array (1MB) D2H  |        44.72 |        59.36 | +32.7% |
| Bytes List (1MB) H2D |        36.87 |        34.82 | -5.56% |
| Bytes List (1MB) D2H |        45.92 |        43.03 | -6.29% |
| Bytes (1MB) H2D      |        54.24 |        54.03 | -0.39% |
| Bytes (1MB) D2H      |        61.61 |        61.21 | -0.65% |
| I32 List …

coredevice: use device endian for kernel and RPC

---

RELEASE_NOTES.rst
artiq/coredevice/comm_analyzer.py
artiq/coredevice/comm_kernel.py
artiq/coredevice/comm_mgmt.py
artiq/coredevice/comm_moninj.py
artiq/coredevice/core.py
artiq/firmware/runtime/analyzer.rs
artiq/firmware/runtime/mgmt.rs
artiq/firmware/runtime/moninj.rs
artiq/firmware/runtime/session.rs

Use device endian for protocols, to make protocols consistent and efficient.
The device would now send a byte at the start of the connection (after receiving magic string) indicating whether the device is using big endian or little endian, and the host would adjust the encoding/decoding according to device endian.
Notes:
1. This breaks existing protocols, users would need to update the firmware to match the host software.
2. Messages for analyzer is still big endian, as that seems to be coded in the gateware, and universal across or1k and zynq.
|   | Type |
```
``` …

Use device endian for protocols

---

artiq/coredevice/comm.py
artiq/coredevice/comm_kernel.py
artiq/coredevice/comm_mgmt.py

This partially reverts commit b5e1bd3, which had removed keepalive. This, however, led to experiments hanging forever if the core device had dropped the connection (e.g. to a kernel CPU panic, or the device being rebooted).
The chosen keepalive settings are fairly conservative (with the 10 s timeout) to avoid any possible interaction with smoltcp's 3 s ARP try interval (see GitHub issue #1150), even though this should be a non-issue now due to the larger ARP cache.
In addition, `CommKernel._read` didn't use to handle empty `recv()` returns correctly. This, like for the usual socket function returning 0, signifies a closed connection. Previously, the worker process would busy-spin forever when that happened.
---
@sbourdeauducq Anything I missed? This makes those kernel CPU crashes much …

coredevice: Re-enable keepalive, don't spin forever on dropped connection

---

RELEASE_NOTES.rst
artiq/coredevice/mirny.py
artiq/frontend/artiq_sinara_tester.py

This patch allows for hardware-revision independent user strings instead of integers for the Mirny reference clock selection. The relevant integer is calculated from the hardware revision read from the CPLD at ``init()``. The change is fully backwards compatible. The ``clk_sel`` functionality is identical to pre-existing code, but the interface is nicer.
Tested against v1.0 and v1.1 hardware on all three global clock sources.
``hw_rev`` is not tested anymore in ``init()``. Removed corresponding fix in ``artiq_sinara_tester``.
Closes #1559 (updated docstring)
|   | Type |
|  | :hammer: Refactoring  |
|  | :scroll: Docs |
```
Longer description. < 70 …
```

mirny: hw_rev independent, human readable clk_sel

---

artiq/coredevice/adf5356.py

The ADF5356 apparently doesn't appreciate getting register changes without being properly initialized. This patch uses the documented register init sequence ([datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ADF5356.pdf) Rev.0 p.32) to perform the detection test (deterministic MUXOUT values).
The slack delays were artificially high so I reduced them. May be that even shorter ones work but this is init so not crucial.
Tested on Mirny v1.0 and v1.1 hardware. Contrary to #1560, the PLL now locks on first try after power up.
Closes #1560 
|   | Type |
```
Longer description. < 70 …
```

coredevice/adf5356: fix initial device detection

---

artiq/tools.py

This patch is a rewrite of ``artiq.tools.file_import`` with the following changes:
- simplify the calculation of the loaded module's name. The new code is equivalent to the old one except if the filename has multiple extensions (e.g. ``exp.test.py``) in which case the resulting module name is not a valid Python identifier but the loader should still work as expected. This should not happen in practice since the filename also doesn't stick to Python module naming conventions. One can revert to the old code if this is an issue (not the core of the PR) but the new one-liner is much more explicit than the old code;
- remove the deprecated call to ``load_module()`` by applying the ``exec_module()``-based recipe from the [docs](https://docs.python.org/3/library/importlib.html#importing-a-source- …

tools/file_import: simplify, remove deprecated load_module() call

---

RELEASE_NOTES.rst
artiq/language/environment.py
artiq/master/worker_impl.py
artiq/test/test_tools.py
artiq/tools.py

This patch:
- refactors the enumeration of experiments from Python modules in ``artiq.master.worker_impl``. In particular, it now uses ``tools.get_experiment`` instead of an almost literal copy of it. This unifies the behavior with ``artiq_run`` and ``artiq_compile`` (or was there a reason not to exclude underscore-prefixed experiments in the master's ``get_exp``?);
- rewrites ``tools.get_experiment`` with ``inspect.getmembers`` instead of ``__dict__``. Introduces a new predicate ``language.is_public_experiment``. The existing ``language.is_experiment`` is not used anywhere in the codebase but is part of the public API. These predicates (or maybe only one) should maybe be moved to ``artiq.tools`` (+ release notes entry);
- rewrites ``master/worker_impl:examine`` with …

master: unify experiments enumeration (+ some tooling unit tests)

---

artiq/test/test_tools.py
artiq/tools.py

The `artiq.tools.get_experiment()` function can now get nested experiment classes.
For example: `artiq.tools.get_experiment(mod, 'Foo.Bar')`.
Not sure if other people are interested in such a feature. We are interested because in this way we can "generate" experiment classes inside other classes that are not experiments. We use this in some specific scenario's. Without this feature, we have to mess with the stack frame to insert the nested class into the global name space for ARTIQ to be able to find it.
|   | Type |
```
``` …

get_experiment() can get nested experiment classes

---

artiq/coredevice/coredevice_generic.schema.json
artiq/frontend/artiq_ddb_template.py

Added by #1601, Mirny now allows the user to indicate the clock selection by one of the following:
* Integer: must be 0, 1, 2 or 3, where the user must choose according to the Mirny board version
* String enum: must be `xo`, `mmcx` or `sma`, where the driver code finds the correct integer value by reading the Mirny board version at initialisation.
Therefore, it is reasonable to add support for both types when validating with jsonschema. This PR also changes `artiq_ddb_template` to ensure double-quoting `clk_sel` when it is a string.
This PR also fixes some styling on jsonschema where `\t` and space characters were mixed.
|   | Type |

jsonschema: Accept String for mirny clk_sel, and fix styling

---

artiq/coredevice/coredevice_generic.schema.json

In #1646, I made a mistake by misplacing the default value for Mirny `clk_sel` in the schema, which rendered the `default` keyword useless. This PR fixes this bug and takes the integer value `0` (representing `xo` for both Mirny versions 1.0 and 1.1) as default.
I chose the integer value as default simply so as to be consistent with the original schema. Should we use `xo` instead?
https://github.com/m-labs/artiq/blob/3844cde97b6445410b95976403ea49cb75914d79/artiq/coredevice/coredevice_generic.schema.json#L372-L377
*This fix is also applicable to ARTIQ-6 as of dbeea7605b8becdace69c893d83a08e10b93a95e, though rebasing would be required.*
|   | Type |
| ✓ | :bug: Bug fix  |

jsonschema: mirny: fix clk_sel default value

---

artiq/coredevice/fastino.py

Currently running `voltage_to_mu()` or `voltage_group_to_mu()` on the host will
convert all machine unit values to int64. This leads to issues when machine units
are returned from RPCs.
This PR allows `xxx_to_mu()` methods for Fastino to return the required int32 type on the core and host device.
|   | Type |

fastino: ensure `xxx_to_mu()` methods return int32 on the host

---

artiq/coredevice/ad9910.py
artiq/coredevice/ad9912.py

AD9910/AD9912 drivers have an optional switch. If the switch is added, the kernel invariants are updated to include this switch. Because the static kernel invariants are defined as a class variable and sets are mutable, the switch is added as a kernel invariant for all instances of the class instead of just one instance. This change makes the kernel invariants an instance variable.
At the same time, additional variables were marked kernel invariant for the same drivers.
This fix should probably also be applied to `release-6` and maybe even older releases.
Closes #1654 
|   | Type |
```
``` …

Fix AD99xx instance kernel invariants

---

artiq/coredevice/ad9910.py
artiq/coredevice/ad9912.py
artiq/frontend/artiq_sinara_tester.py
artiq/test/coredevice/test_ad9910.py
artiq/test/coredevice/test_urukul.py

Fixed bug in type annotations for `cfg_sw()` functions of AD9910/AD9912/Urukul. Now the `state` argument is always a `TBool`. Updated test cases accordingly.
Probably introduced by me in #1618 .
closes #1642
|   | Type |
```
```

Fixes AD99xx/Urukul type annotations for cfg_sw()

---

artiq/coredevice/comm_kernel.py
artiq/test/coredevice/test_embedding.py

Fixes type persistency of int64-based lists across RPCs.
```python
class TestListInt64Writeback(EnvExperiment):
self.values = [int64(1)] * 2
def run(self):
self.print_rpc("Initially", self.values)
self.messup()
self.print_rpc("After first writeback", self.values)
self.stress()
self.print_rpc("After second writeback", self.values)
@kernel
def stress(self):
self.values[0] = self.core.get_rtio_counter_mu()
self.print_rpc("RPC from 'stress()'", self.values)
@kernel
def messup(self):
for i in range(len(self.values)):
self.values[i] = int64(0)
self.print_rpc("RPC from 'messup()'", self.values)
def print_rpc(self, msg, values):
print("{}: type({}): {}".format(msg, values, [type(value) for value in values]))
```
This experiment prints the following: …

coredevice.comm_kernel: Fix unpacking of lists of int64

---

artiq/coredevice/coredevice_generic.schema.json

When validating with jsonschema, if `target` is `kasli`, `enable_sata_drtio` must be `false` (which is the default value) unless `hw_rev` is v1.0 or v1.1.
This respects the FPGA bank I/O definitions on [Migen](https://github.com/m-labs/migen/blob/master/migen/build/platforms/sinara/kasli.py). For example, v2.0 in fact does not have a SATA connector.
Prior to this PR, if `enable_sata_drtio` is `true` for Kasli v2.0 targets, simply a `Resource not found` error is raised from Migen when the SoC builder is called from `gateware.targets.kasli_generic`. An error raised from JSON validation, instead, might be more helpful than the error raised by Migen.
|   | Type |
|   | …

jsonschema: only allow enable_sata_drtio=true for Kasli if v1.0/1.1

---

artiq/remoting.py

Wrap the remote SSH commands of `artiq_flash` (using paramiko) in a bash login shell.
The login shell will load the nix environment on non-nixos systems, required to get openocd in `$PATH` when installed in the nix environment of a system.
See also https://forum.m-labs.hk/d/182-remote-artiq-flash-openocd-command-not-found
I do not have a NixOS system, so I have only tested the changes on Ubuntu 20.04.
It would be nice to have this fix also in the `release-6` branch.
|   | Type |
```
```
See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyr …

artiq_flash: wrap paramiko commands in bash login shell

---

artiq/frontend/artiq_ddb_template.py
artiq/gateware/targets/kasli_generic.py

Fix the problem described by issue #1623. Now we can control 2 LEDs on the front panel of Kasli v2.0 like the documentation of ARTIQ
Closes #1623 
|   | Type |
```
```

Kasli: Added front panel user LED (#1623)

---

artiq/master/databases.py
artiq/test/test_device_db.py

Refactor ``artiq.master.databases:device_db_from_file`` and make use of ``artiq.tools.file_import`` instead of manual file execution.
This conveniently simplifies splitting the ``device_db`` over multiple files, as is commonly (?) done when augmenting the template generated by ``artiq_ddb_template`` (see e.g. [#1410 (comment)](https://github.com/m-labs/artiq/issues/1410#issuecomment-567752076)). Prior to this patch, one needed to add the location of the imported module to ``sys.path`` manually in the top-level ``device_db.py``.
This patch also adds basic interface unittests for ``artiq.master.databases.DeviceDB``. All new tests except ``test_import_same_level`` pass prior to applying the patch.
|   | Type |
|   | :sparkles: New …

Use tools.file_import to load the device_db

---

artiq/compiler/embedding.py

According to PEP484, type hint can be a string literal for forward references. With PEP563, type hint would be preserved in annotations in string form.
|   | Type |
Test cases:
```python
class ArtiqTest(EnvExperiment):
self.setattr_device('core')
@kernel
def run(self):
self.foo(1)
@kernel
def foo(self, v: 'TInt32'):
self.core.reset()
print('foo=', v)
```
The original version would fail with error message
```
test.py:14:1: error: type annotation for argument 'v', ''TInt32'', is not an ARTIQ type
def foo(self, v: 'TInt32'):
^                          
test.py:14:1: note: in kernel function here
def foo(self, v: 'TInt32'):
^                          
test.py:11:9-11:17: note: while …
```

compiler: allows string annotation

---

artiq/compiler/embedding.py

Fixed test failure, and can now evaluate complex annotations. (which I forgot earlier...)
|   | Type |
Tested with `artiq.test.coredevice.test_embedding`. Also tried adding the line `from __future__ import annotations` to make all annotations as string literal for testing.
```
```

compiler: fixed embedding annotation evaluation

---

artiq/coredevice/comm_moninj.py

Use `readexactly` so that `struct.unpack` will always have the right length to unpack. 
Closes #1727
|   | Type |
```
```

moninj: change read to readexactly to avoid unpack failure

---

artiq/coredevice/ad53xx.py
artiq/coredevice/zotino.py

Unify the default SPI read clock divisor (`div_read`) for both `Zotino` and `AD53xx` at 16. Plus minor update to the documentation.
|   | Type |
Currently, `AD53xx` and `Zotino` have different default SPI clock speeds for readbacks. According to 99f7672c79b4fd9e3fa400caeea16d33155b62ff, `AD53xx` has switched the divisor value from 8 to 16 but `Zotino` has never been changed.
The motivation is that reads should take longer duration than writes because of variable round-trip delays in various types of device connection (e.g. DRTIO vs VHDCI).
Now, using default Zotino settings, the SPI clock for reading AD53xx registers will be halved. This will make …

zotino: Unify default SPI read clock divisor at 16

---

artiq/frontend/artiq_sinara_tester.py

This PR implements testing of SUServos with artiq_sinara_tester. The servo loops are checked by setting only proportional gain and comparing the RF output powers at different input Voltages. 
Some modification to the ddb interpretation was necessary so that Urukuls associated with SUServos won't get tested by the Urukul testing procedure.
Close #1658 
|   | Type |
The changes were tested on hardware with a master-satellite system with two SUServos. Additionally, robustness of the tester script was checked with several ddbs with different combinations of Urukuls and SUServos.
```
Longer description. < 70 …
```

Suservo tester

---

RELEASE_NOTES.rst
artiq/coredevice/phaser.py

When starting with Phaser, it is not totally obvious how to align updates to the RTIO timeline. This patch introduces `get_next_frame_timestamp()` for the following usage (`phaser0.channel[0]` DUC-only single-tone output phase is stable with respect to the output trigger on `ttl4`):
```python
class PhaserDeterministicLatency(EnvExperiment):
self.phaser = self.get_device("phaser0")
self.trg = self.get_device("ttl4")
@kernel
def run(self):
self.core.reset()
self.phaser.init(debug=True)
self.trg.output()
self.phaser.channel[0].set_duc_frequency(102 * MHz)
self.phaser.channel[0].set_duc_cfg(clr_once=1)
self.phaser.channel[0].set_att(0 * dB)
self.phaser.channel[0].oscillator[0].set_amplitude_phase_mu(
asf=0x7FFF >> 2, …
```

Phaser: add helpers to align updates with RTIO timeline

---

artiq/frontend/artiq_flash.py

This allows the user to flash (i.e. with `rtm_gateware` as an action) or load (`rtm_load`) bistreams for Sayma RTM in the absence of the Sayma AMC binaries and bitstreams.
Prior to this fix, the user must create a dummy directory (e.g. named `satellite`) inside the `--dir` path, in order to perform any of the above non-AMC specific actions. Otherwise, `artiq_flash` will raise `FileNotFoundError: no variants found, did you install a board binary package?`.
|   | Type |

artiq_flash: Allow flashing Sayma RTM even if AMC artifacts are missing

---

RELEASE_NOTES.rst
artiq/firmware/libboard_artiq/drtioaux.rs

DRTIO messages are now 64-bits aligned. See discussion in #1779.
Tested with Kasli v1.1 and Kasli v2.0 using DRTIO.
Closes #1779
|   | Type |
```
```

Fix DRTIO message alignment

---

RELEASE_NOTES.rst
artiq/coredevice/coredevice_generic.schema.json
artiq/gateware/targets/kasli.py
artiq/gateware/targets/kasli_generic.py

This patch adds an entry to the JSON hardware description file for Kasli to configure the number of FIFOs in the SED.
Moderately increasing the number of lanes (from 8 to 16 lanes) seems to be unproblematic and greatly helps mitigating sequence errors. The JSON schema sets the limit to 32, since this is the maximum I got to build using Vivado 2020.1.
An extension of this patch may be to expose more gateware configuration options in the JSON file, but this is probably very error prone.
|   | Type |
|  | :bug: Bug fix  |
```
``` …

kasli: add SED lanes count option to HW description JSON file

---

RELEASE_NOTES.rst
artiq/firmware/satman/main.rs
artiq/gateware/drtio/siphaser.py
artiq/gateware/targets/kc705.py

This pull request adds support for 100MHz DRTIO clock for KC705 and Kasli. The PLL and VCO frequency parameters have been checked with the datasheets for these boards and it's well within specs.
For Kasli, frequency is chosen within the JSON file ("rtio_frequency" key); for KC705 it's an additional argument for building.
Additionally, this PR includes changes in the siphaser, meaning it must be merged before the corresponding PR in artiq-zynq repo.
|   | Type |
```
```
ARTIQ files that do not contain a license …

Support for DRTIO 100MHz

---

RELEASE_NOTES.rst
artiq/coredevice/comm_kernel.py
artiq/firmware/libproto_artiq/session_proto.rs
artiq/firmware/runtime/rtio_mgt.rs
artiq/firmware/runtime/session.rs

When an asynchronous error such as RTIO channel collision, there no indications nor hints to tell the host something wrong happened. This PR tries to inform the host as best as possible. High latency DRTIO are yet to be tested, plus the use of network in DRTIO will be very tricky to handle (per https://github.com/m-labs/artiq/issues/1644#issuecomment-806897336).
Closes #1644
|   | Type |

Host report for async error upon kernel termination

---

artiq/coredevice/ad9910.py
artiq/coredevice/ad9912.py

1. Fixed typing errors in AD9910 driver and added a few return types
2. Added default pow to `set_mu()` for AD9912 (to match other `set()` function(s))
|   | Type |
```
```

Fixes for AD9910 and AD9912 drivers

---

artiq/compiler/transforms/llvm_ir_generator.py

Signed-off-by: Steve Fan <sf@m-labs.hk>
There is a minor stack errata that made some pointers dangling after restoring the stack.
https://github.com/m-labs/artiq/blob/9e5e234af31a82d053bc6c1add9eedc8bcf1d99b/artiq/compiler/transforms/llvm_ir_generator.py#L1252-L1257
This creates a potential "use-after-free" scenario (there is no `free` since this is all on stack, however, so it is more like invalid stack pointer), but this is still protected by PMP supposedly.
Closes #1798
|   | Type |

llvm_ir: move stacksave before lltag alloca in build_rpc

---

RELEASE_NOTES.rst
artiq/master/worker_db.py

When using `get_dataset()` to obtain a key that was stored persistent, the value is added to the archive of the dataset manager.
When using `set_dataset()` with a key that was archived earlier, you get the following warning:
```
WARNING:worker(219,artiq_test.py):artiq.master.worker_db:Modifying dataset 'foo' which is in archive, archive will remain untouched
```
I think this warning is overkill as this is the expected behavior of the archive. Nevertheless, the log can have many of these warnings. The warning especially appears when we load calibrated values from the persistent datasets and update some of these calibration values at the end of the experiment.
If others agree, I propose to remove this warning.
|   | Type |
| ✓  | :sparkles: New feature? | …

Remove worker_db warning for writing a dataset that is also in the archive

---

artiq/compiler/ir.py
artiq/compiler/transforms/artiq_ir_generator.py
artiq/compiler/transforms/llvm_ir_generator.py

This PR fixes exception handling issues in ARTIQ.
1. Try blocks without a final block will not be generated as a cleanup block. Together with firmware changes, we should be able to improve exception unwinding speed, as the landingpad catch clauses can be filtered in the firmware before executing the body. This change should be backward compatible with the old firmware as the old personality function does not check for catch clauses (it will execute the landingpad anyway).
2. Fixes dead code eliminator bug regarding landingpad. Landingpad clauses were not removed previously which would cause assertion errors.
3. Fixes code generation for rethrow together with final block. The code generation was correct (except that the exception has to be lazy evaluated to make sure that it is generated …

Landingpad

---

artiq/coredevice/ad9910.py
artiq/coredevice/urukul.py
artiq/gateware/suservo/dds_ser.py

This PR patches the issues originated from the change of default profiles in #1584.
- AD9910 & Urukul drivers now uses the default single tone profile `DEFAULT_PROFILE` (7) as the default value of both `set`/set_mu` & `get`/`get_mu` (#1809).
- RAM profile setter uses `DEFAULT_PROFILE_RAM` (0) as default.
- SU-Servo gateware now sends to the default single tone profile.
`DEFAULT_PROFILE` concerns the default value of CPLD shift register and AD9910 itself, so it is in `urukul.py`.
`_DEFAULT_PROFILE_RAM` is only referenced in AD9910, and only AD9910 has RAM mode, so it is in `ad9910.py`.
I need some feedback about the constants.
Ran the code in the example of #1817 and getting RF signal from Urukul, controllable by Sampler.
#1809 (RAM FTW/ASF/POW getter is not ported to `get`/`get_mu`) …

Urukul/SU-Servo: Use constants for default profiles

---

artiq/frontend/artiq_sinara_tester.py

Update `artiq_sinara_tester` to match the changed API since in #1500.
Tested on a Sinara crate with SU-Servo installed (1 DDS).
Closes #1814
|   | Type |
```
```

artiq_sinara_tester: fix outdated API

---

artiq/coredevice/comm_kernel.py

Signed-off-by: Steve Fan <sf@m-labs.hk>
Adds missing type validator in `_send_rpc_value` when handling list of i32 and i64 types by checking `struct.error` and throw a RPCReturnValueError.  
|   | Type |

comm_kernel: check if elements are within bounds for RPC list

---

artiq/coredevice/comm_kernel.py

This PR fixes an issue when an exception happens after running the service function in RPC service routine. Previously I tried to catch `struct.error` as a quick fix, but it seems like the fundamental issue is not just because of that. 
The problem started with this part, after running the service routine:
https://github.com/m-labs/artiq/blob/bbac4770926048b3c0b434aede371a63d198ecd5/artiq/coredevice/comm_kernel.py#L561-L564
And when an exception happened around that part:
https://github.com/m-labs/artiq/blob/bbac4770926048b3c0b434aede371a63d198ecd5/artiq/coredevice/comm_kernel.py#L568-L572
It is possible that the `RPCException` is being mistaken as part of the `RPCReply`, which is going to confuse the host kernel.
One possible way of fixing this is to discard the write buffer when an …

comm_kernel: only send replies when no user-defined RPC function throws in service

---

artiq/gui/entries.py

This solves an issue where the dashboard value will appear to go out of bound when the default initial value on dashboard refresh is less than the minimum value of the argument (not rendered correctly). This could be solved with a forced re-render, but it is much better to handle it by setting the default value to min if min is positive, and 0 if min is negative
Closes #1811 
|   | Type |

prioritize min as part of default value resolution in dashboard

---

artiq/firmware/libproto_artiq/rpc_proto.rs
artiq/test/coredevice/test_embedding.py

Backporting of https://git.m-labs.hk/M-Labs/artiq-zynq/pulls/160 to master
Closes #1810
|   | Type |

Backport of "fixes alignment and size problem" from artiq-zynq

---

artiq/coredevice/comm_moninj.py

> For a TCP socket would not disconnect immediately if the connection to core device is suddenly disrupted (e.g. power loss, panic), because we have TCP retransmission (RTT) and SYN retry window as some form of compromises in difficult network situations (and this explains why the stream drops only after 10 seconds or so).
> 
> As such it is better to set SO_KEEPALIVE in order to stop the proxy as soon as the connection stops.
Note: SYN retries and TCP retransmissions can be tuned by changing `/proc/sys/net/ipv4/{tcp_syn_retries,tcp_retries1,tcp_retries2}` in Linux. 
For Windows it is controlled by `TcpMaxDataRetransmissions` and `TCPInitialRtt` under `HKLM\System\CurrentControlSet\Services\Tcpip\Parameters` in WIndows registry. There is no straightforward way to control RTT in Linux …

comm_moninj: set lifetime for socket

---

artiq/coredevice/adf5356.py
artiq/coredevice/mirny.py
artiq/frontend/artiq_sinara_tester.py

This PR adds `set_att` methods to Mirny and ADF5356 classes, so attenuation can be set directly using decibel.
The dB-to-mu conversion is identical to the implementation in Urukul.
The line that sets the attenuation of a Mirny channel in `artiq_sinara_tester` is also changed to use the new method.
- Tested with bladeRF, output power of each channel changes accordingly when `ADF5356.set_att()` is invoked.
- Mirny v1.1 tested successfully with `artiq_sinara_tester`.
- Compared `set_att_mu(160)` and `set_att(11.5*dB)` in `artiq_sinara_tester`. The same peak is observed in Gqrx.
|   | Type |
```
```
See [copyright & …

Mirny: set attenuation value from decibel

---

artiq/frontend/artiq_flash.py

Fixes flashing when a --dir argument isn't set. If --dir isn't set then `binary_dir` will be `None` and `os.path.join` will throw a `ValueError`. This can happen if for example you're flashing the storage.
|   | Type |

Don't try to make rtm_binary_dir if binary_dir unset

---

artiq/dashboard/explorer.py
artiq/frontend/artiq_dashboard.py

Add an action on the context menu of explorer dock that reloads device database
|   | Type |

dashboard: add device database reload action on context menu

---

flake.nix

Nix changed their configs (for example, they settled on hyphen-style instead of camelCase and allowed ``extra-`` instead of full overwrite), making flakes in artiq not override the configs as they should. This should fix exactly that. That includes both binary substituters and sandbox paths.
Closes #1852 
|   | Type |

flake: fix configuration over

---

artiq/test/coredevice/test_i2c.py

Quick fix for i2c switch test with appropriate annotation.
Tested with kc705 (``artiq_run`` with modified version)
|   | Type |

test_i2c: fix for missing readback

---

artiq/frontend/artiq_flash.py

This should fix flashing boards that don't explicitely end with "satellite" (e.g. when there's "satellite1" and "satellite2").
Tested with a dry run on a ``cqtsatellite1`` board.
|   | Type |

release-6: artiq_flash: fix for satellite boards

---

artiq/compiler/transforms/llvm_ir_generator.py
artiq/firmware/ksupport/lib.rs
artiq/firmware/libproto_artiq/kernel_proto.rs
artiq/firmware/libproto_artiq/rpc_proto.rs
artiq/firmware/runtime/cache.rs
artiq/firmware/runtime/session.rs

Changed list representation from `CSlice<T>` to `&CSlice<T>`. 
Closes #1833 
|   | Type |
```
```

List representation

---

artiq/compiler/transforms/llvm_ir_generator.py

Added stack save for alloca calls during FFI function preamble (in LLVMIRGenerator._prepare_ffi_call).
Without this, a syscall with args that need to be allocated (such as TStr) will cause the stack pointer to be permanently decremented, similar to the issue fixed in #1802.
I have tested this by configuring a syscall to print the address of a variable allocated on the stack. The syscall accepts a TStr as an argument, and repeatedly decrements the stack pointer by 8 when called successively.
Without this PR:
```
[    49.278399s]  INFO(kernel): Stack pointer: 0x4ffffe78
[    49.283415s]  INFO(kernel): Stack pointer: 0x4ffffe70
[    49.288464s]  INFO(kernel): Stack pointer: 0x4ffffe68
[    49.293513s]  INFO(kernel): Stack pointer: 0x4ffffe60
```
With this PR:
```
[    92.268171s] …
```

llvm_ir: stack leak on ffi call

---

artiq/browser/files.py

ARTIQ browser handles HDF5 groups correctly instead of crashing.
This is a fix for release 6, but both commits can be cherry-picked onto master.
Closes #1879 .
|   | Type |
```
```

Fix ARTIQ browser HDF5 group handling

---

flake.nix

Useful while working on the legacy compiler.

flake: Add compiler test prerequisites to devShell

---

artiq/applets/progress_bar.py
artiq/gui/applets.py

A small QtQuick widget to realize a progress bar for datasets. This can be useful if you have some kind of run counter.
* It has as much documentation as `artiq.applets.big_number` has :sweat_smile:
* code is working in our production env, tested as standalone window and inside the dashboard
* commits can potentially be squashed
https://github.com/m-labs/artiq/pull/1792
|   | Type |
```
```

Add feature/qtprogressbar to master

---

RELEASE_NOTES.rst
artiq/coredevice/coredevice_generic.schema.json
artiq/frontend/artiq_ddb_template.py
artiq/gateware/eem.py
artiq/gateware/eem_7series.py
artiq/gateware/rtio/phy/ttl_simple.py

TTLClockGen module is available already, but it's not exposed in JSONs. While the class is used in KC705-based systems, but for Kasli it was not yet possible to have DIO clock generation available. This PR only allows usage of clockgen with kasli systems.
Tested by running a simple ARTIQ experiment using the clockgen and looking at the output on oscilloscope.
|   | Type |
```
```

Expose TTLClockGen for Kasli JSONs

---

artiq/coredevice/comm_mgmt.py
artiq/firmware/libboard_misoc/config.rs
artiq/firmware/runtime/session.rs

After recent changes, master with not configured DRTIO routing table would display the following warning in the logs:
```
WARN(board_artiq::drtio_routing): length of the configured routing table is incorrect
```
This error was misleading in that it could cause the user to think there was some sort of data corruption at play. 
This was caused by ``libboard_misoc`` ``config::read`` returning an empty value if the key was not found - so other code had also to check if the returned value's length was bigger than 0. 
Funnily enough, ``config::read_str`` handles any missing data or other errors and returns its own UTF8 error - so in a way that was already covered.
After this change, the warning disappears and no other firmware code is affected - although I did remove the check from …

libboard_misoc: config::read returns Error instead of empty value if key was not found

---

artiq/firmware/libdyld/lib.rs

This PR is the runtime linker portion to nac3ld. As nac3ld does not generate unnecessary sections such as PLT & GOT, this patch relocates directly onto the .text section.
Due to the lack of PLT, symbol rebinding cannot be completed just by solely updating a value. The linker will instead attempt to apply the new value to all PLT relocated value.
See nac3ld PR in NAC3.
#1883
[NAC3 PR 292](https://git.m-labs.hk/M-Labs/nac3/pulls/292)
|   | Type |
```
```
ARTIQ files that do not contain a license header are …

libdyld: Support nac3ld

---

artiq/frontend/artiq_master.py
artiq/master/scheduler.py
artiq/master/worker_impl.py
artiq/test/test_scheduler.py

add log_tuples function which can write the runid, start_time and path to a file in the data directory
Log runid/start_time/path tuples to a file in the data directory #810 
|   | Type |
```
add log_tuples function
```

add log_tuples function

---

artiq/dashboard/experiments.py
artiq/dashboard/moninj.py
artiq/frontend/artiq_dashboard.py

This PR adds ability to set DDS channel frequency in the dashboard. Works with AD9914, AD9912, AD9910.
It works by generating a kernel with given frequency and sending it by content to the device.
The widget for each channel displays the frequency as before. If you move your cursor over one, OVR button will pop up:
And if you press it, you will be able to change the frequency, and either apply or cancel the changes. Using Enter keys to apply and Esc to cancel works as well.
Tested with kc705 (looking into logs, kernel is run, not verified AD9914 functionality), and a Kasli with an AD9912. The core functionality works - frequency can be easily changed - but has some limitations:
- new frequency is not displayed in the menu (moninj does not report it back, I suppose?). I suppose displaying …

[WIP] Dashboard: DDS Injection

---

artiq/frontend/artiq_dashboard.py
artiq/gui/applets.py

This facilitates applets that connect back to the master
(e.g. to update datasets on user request, as used by ndscan).

applets: Add ${server}, ${port_control}, ${port_notify} command substitutions

---

artiq/firmware/runtime/rtio_mgt.rs

Update the SEEN_ASYNC_ERRORS and add unsafe to it 
destination_survey should update SEEN_ASYNC_ERRORS #1895 
|   | Type |
```
```

Update seen async errors

---

artiq/frontend/artiq_dashboard.py

Together with m-labs/artiq#1916, this allows the user to integrate multiple argument UIs implemented in external libraries.
For only one plugin, this could just be implemented by a wrapper module around `artiq_dashboard` that does the necessary registration/… before forwarding to `artiq.frontend.artiq_dashboard.main`, but this also works with multiple independent plugins and avoids users having to deal with any nonsense regarding module lookup paths/executable wrapper scripts/…

dashboard: Add cmdline option to load plugins on startup

---

artiq/dashboard/experiments.py
artiq/frontend/artiq_dashboard.py

This is analogous to the explist/schedule subscribers, and allows
custom argument editors (such as ndscan) to provide hints/defaults/…
from datasets once available.

dashboard: Plumb through datasets client to ExperimentManager

---

artiq/dashboard/experiments.py

These are used by ndscan, as re-serialising the entire ndscan
parameter metadata tree, which can grow to be quite extensive,
on every single Qt change event is a bit excessive (and would
probably cause a bit of lag while typing for big experiments
on low-end machines).

dashboard: Add submit/close hooks for custom argument editors

---

artiq/frontend/aqctl_corelog.py

Replace asyncio.open_connection with async_open_connection that
has keepalive
Put get_logs_task inside asyncio.wait() for termination when
disconnected
|   | Type |
```
```

Disconnect corelog properly when core device connection failed

---

artiq/dashboard/moninj.py

On first run of setting frequency on AD9912 there's a chance of an RTIO underflow. This PR is intending to fix that.
Tested with real hardware, and as expected it doesn't happen anymore.
|   | Type |
```
```

moninj: fix underflows for urukul freq set

---

artiq/language/environment.py

**Problem**: scheduler device might have added incorrect arguments as stated in issue #1641
**Solution**: Check the unused arguments in expid in unprocessed_arguments after build
**Details**: remove argument in unprocessed_arguments after get() during build. Call check_unused_arguments() after build to see what argument is left. Raise exception and state those arguments.
**Test result**:
Based on the example in #1641 
After submitting RID 40, exception occur and stating what arguments were not being used.
After correcting the typo, submit it as RID 42 and successfully changed the text output.
|   | Type |
```
topic: description. < 50 characters …
```

language.environment: Add check_unused_arguments

---

doc/manual/installing.rst

In the docs the ``afws_client`` example has wrong argument order - it's build folder then variant name, not variant then folder.
|   | Type |
```
```

afws_client docs: fix argument order

---

artiq/frontend/artiq_compile.py
artiq/frontend/artiq_run.py
artiq/language/environment.py
artiq/master/worker_impl.py

`check_unprocessed_arguments` is called potentially before all arguments have had a chance to be processed.
Check for unprocessed arguments only in instances of `Experiment`.
Check if `self` is an instance of `Experiment` before calling `check_unprocessed_arguments`. This ensures that the argument manager has been able to process all arguments built in `HasEnvironment` sub-components.
Based on the experiment in issue [#1641](https://github.com/m-labs/artiq/issues/1641)
``` python
class SubComponent1(HasEnvironment):
self.setattr_argument(
"propaganda", StringValue(default="Brainwash population")
)
@kernel
def do(self):
print(self.propaganda)
class SubComponent2(HasEnvironment): …
```

language: check for unprocessed arguments after constructing experiment

---

artiq/master/worker_impl.py

Large datasets were not being saved properly: see https://forum.m-labs.hk/d/519-how-large-can-a-dataset-be-before-there-is-a-problem-with-saving-hdf5/11 for an exploration. 
This was due to a race condition in
https://github.com/m-labs/artiq/blob/58cc3b8d0a957b24834e08cb3fbe70c148fd17b4/artiq/master/worker_impl.py#L347-L356
...where the worker was reporting that it had finished before it had actually started saving HDF5 files. It then had two seconds before the timeout in 
https://github.com/m-labs/artiq/blob/58cc3b8d0a957b24834e08cb3fbe70c148fd17b4/artiq/master/worker.py#L123-L134
...killed it. 
|   | Type |
```
topic: description. < 50 characters …
```

Fix large datasets not saving

---

artiq/compiler/transforms/artiq_ir_generator.py
artiq/compiler/transforms/inferencer.py
artiq/test/lit/embedding/error_tuple_index_assign.py
artiq/test/lit/embedding/index_tuple.py
artiq/test/lit/inferencer/error_tuple_index.py
artiq/test/lit/integration/tuple_index.py

This allows for indexing tuples with a constant integer value (e.g. `x[0]`), rather than having to unpack them (`a, _b, _c = x`).
There is some discussion of this in #656 as one of the pain points, and we've definitely had to work around it a few times in our own code.
|   | Type |
Have tested the compiled code on a Kasli 1.1 master.

Allow indexing tuples in kernel code

---

RELEASE_NOTES.rst
artiq/gui/applets.py

I had introduced this in f11aef74b as a means of quickly cleaning up
after e.g. an exploratory session where a lot of transient applets were
opened from ndscan, or for a dashboard that has been running for a while
with CCBs enabled, but without anybody actually working here.
It turns out that one usually wants the few docked applets, which
necessarily have been manually arranged, to stay open. Hence, this
adds an option to preserve docked applets, and makes the keyboard
shortcut default to this.
Since the "Close all applets" option was specifically introduced as
a convenience for these situations, we might choose to remove it
altogether.

dashboard: Option to close all non-docked applets; make Ctrl-Alt-W default to it

---

artiq/compiler/embedding.py
artiq/test/lit/embedding/mixed_tuple.py

The type checker/inferer visits every node in an AST tree, including function return annotations. This means for a function definition like
def f() -> TTuple([TInt32, TBool]):
...
We attempt to type check the list `[TInt32, TBool]`, which generates the unification constraint `builtins.TBool ~ builtins.TInt`. This then fails, causing the program to not compile.
We can avoid this by just clearing the return annotation in the embedding stage. The return type isn't actually used anywhere (as it's extracted from the run-time function, rather than the AST), so this is entirely safe. Arguments aren't affected by this, as we already cleared out the annotation (see [`visit_arg` in `embedding.py`](https://github.com/m-labs/artiq/blob/e8818c812c84ad232e5e899fd43df97138d1dea4/artiq/compiler/embedding. …

Fix return type annotations being type-checked as expressions

---

artiq/compiler/transforms/inferencer.py
artiq/test/lit/embedding/error_with_rpc.py

Attempting to use Python's `with` syntax on a non-kernel class will crash the compiler, as it currently assumes `__enter__` and `__exit__` are kernel functions. This adds an additional check beforehand to flag this.
The error message itself is not great (RPC type signatures are ugly!), but it does point to the `with:` block, which in most cases makes the problem obvious. I'm open to suggestions here though!
|   | Type |

Report non-kernel `__enter__`/`__exit__` methods

---

artiq/test/lit/embedding/error_with_rpc.py

This fixes the error message in the `error_with_rpc` test (see #2660). In 005630ca93aac06cc96066d7cd5e4ed7a6e76960 I updated the error message, but failed to update the test — really sorry about that!
|   | Type |

Update error_with_rpc to reflect changes in error message

---

artiq/master/experiments.py

I am currently writing an alternative dashboard in a separate git repository, which features experiment file text editing as the user selects an experiment from the explorer. Thus, the dashboard needs to know the root of the experiment repository. It may ask the `artiq_master` explicitly via the `pc_rpc` interface and `artiq_master` returns the desired string.
|   | Type |

experiments: expose repo backend root for use in dashboard via pc_rpc

---

artiq/gui/tools.py

Closes #2783 
Testing:
+ Saving a channel list is broken before this fix, works afterwards.

gui.tools: fix qt6 enum

---

RELEASE_NOTES.rst
artiq/browser/experiments.py
artiq/browser/files.py
artiq/compat.py
artiq/dashboard/experiments.py
artiq/dashboard/waveform.py
artiq/frontend/artiq_client.py
artiq/frontend/artiq_run.py
artiq/gui/state.py
artiq/language/environment.py
artiq/master/databases.py
artiq/tools.py
flake.lock
flake.nix

This switches ARTIQ over from PYON v1 to PYON v2 (https://github.com/m-labs/sipyco/pull/64).
Migration to PYON v2:
- Serialized data is always stored as PYON v2. Ensure backups of existing PYON v1 data
exist before starting ARTIQ-9. Keep a backup of the PYON v1 dataset DB.
- Both PYON v1 and PYON v2 sipyco pc_rpc controllers are supported simultaneously.
PYON v2 support will be required in a future sipyco/ARTIQ release.
- Custom applets, sync_struct/broadcast consumers (dataset db, scheduler, log, experiment db)
require PYON v2: ensure sipyco v2 is used.
- When PYON v2 decoding fails in the following contexts, decoding as PYON v1 is attempted.
The support for PYON v1 decoding will be removed in a future ARTIQ release.
+ Dataset DB file
+ HDF5 results ``expid``. Note that existing files …

sipyco with PYON v2
